Short lived committee assignments should not be added to ENR attnets
ChainSafe/lodestar pull request #1002
Opened 2020-06-10 09:05 UTC by tuyennhv

## Goals
+ resolves #959 
+ Address this snippet in the spec
```
Note: When preparing for a hard fork, a validator must select and subscribe to random subnets of the future fork versioning at least EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION epochs in advance of the fork. These new subnets for the fork are maintained in addition to those for the current fork until the fork occurs. After the fork occurs, let the subnets from the previous fork reach the end of life with no replacements.
```

2020-06-15 10:46 UTC, mpetrunic requested changes

2020-06-15 10:46 UTC, mpetrunic commented on packages/lodestar/src/tasks/tasks/interopSubnetsJoiningTask.ts
> +        setTimeout(this.run, timeToPreparedEpoch, nextForkDigest, this.nextForkSubnets);
this will prevent node from exiting. It should be cleaned on stop

2020-06-15 20:07 UTC, wemeetagain reviewed
lgtm minus @mpetrunic 's comment

2020-06-15 20:07 UTC, wemeetagain commented on packages/lodestar/src/chain/blocks/process.ts
> +            eventBus.emit("forkVersion");
not necessary for this PR, but we should include the "important" metadata in the event, too (eg: currentVersion and epoch)

2020-06-16 04:32 UTC, wemeetagain approved these changes

2020-06-16 04:32 UTC, merged