Error handling
ChainSafe/lodestar pull request #1030
Opened 2020-06-18 10:23 UTC by mpetrunic

- set fastify error handler to log unintentional errors
- add api logger with fastify adapter
- handler api rejections in lodestar-validator

2020-06-18 17:11 UTC, wemeetagain requested changes

2020-06-18 17:11 UTC, wemeetagain commented on packages/lodestar/src/api/rest/logger/fastify.ts
> +  private winston: ILogger;
I think should be called something like `log` or `logger` since this is generic `ILogger`

2020-06-19 03:17 UTC, tuyennhv commented on packages/lodestar-validator/src/services/attestation.ts
> +      this.logger.error("Failed to publish signed aggregate and proof");
Log `e.message` here

2020-06-24 22:46 UTC, wemeetagain approved these changes

2020-06-25 07:35 UTC, twoeths approved these changes

2020-06-25 07:48 UTC, merged