Process slot logic
ChainSafe/lodestar pull request #111
Opened 2019-02-16 23:04 UTC by wemeetagain

Add slot processing
Add

2019-02-16 23:42 UTC, GregTheGreek approved these changes

2019-02-17 01:20 UTC, ansermino requested changes

2019-02-17 01:20 UTC, ansermino commented on beaconChain/helpers/stateTransitionHelpers.ts
> +  const o: bytes[] = Array.from({ length: values.length },
Please add comment

2019-02-17 01:20 UTC, ansermino commented on beaconChain/helpers/stateTransitionHelpers.ts
> +      .concat(values.map((v) => hash(v)));
Shouldn't hash

2019-02-19 22:03 UTC, ansermino approved these changes

2019-02-20 01:46 UTC, merged