Wire in chain processing logic
ChainSafe/lodestar pull request #138
Opened 2019-03-23 21:41 UTC by wemeetagain

This puts the state transition logic together into a chain module.

- eth2genesis handling is mostly complete
  - the chain module listens to the eth1 module for the eth2genesis event, then creates the genesis state/block and stores in the db
- Block processing is wired in, with minor adjustments to the underlying logic
- Fork choice is stubbed out, not currently using our lmd ghost
- needs tests for
  - genesis event
  - processing block
  - applying fork choice rule

2019-03-23 22:14 UTC, GregTheGreek commented
IM SO EXCITED GREAT WORK

2019-03-23 22:15 UTC, GregTheGreek commented
CC: @decanus THIS IS PROGRESS

2019-03-23 23:26 UTC, GregTheGreek requested changes
First pass through main thing is make sure to get those JSDoc comments in.

I'll do a logic pass through shortly

2019-03-23 23:26 UTC, GregTheGreek commented on src/chain/index.ts
>    public async start() {
Add space and jsdoc :)

2019-03-23 23:26 UTC, GregTheGreek commented on src/chain/index.ts
> +  public async processEth2Genesis(genesisTime: uint64, genesisDeposits: Deposit[], genesisEth1Data: Eth1Data) {
jsdoc please :)

2019-03-27 19:24 UTC, GregTheGreek commented
Just went through all the logic one more time, everything seems very solid imo and would be good for a PR depending on how much more logic you want to add in

2019-03-27 19:51 UTC, wemeetagain commented
Yeah, I think we should merge this and add further functionality in later PRs. I think it will be easier to debug the state transition stuff once we move our slots/epochs/validator indices from bignums to numbers.

2019-03-29 17:43 UTC, wemeetagain commented
This should be ready for re-review.
The failing tests are from rebasing on master, looks like linter errors from the recent validator client work.

2019-03-29 18:31 UTC, GregTheGreek approved these changes

2019-03-29 18:46 UTC, merged