spadina testnet lodestar-cli setup
ChainSafe/lodestar pull request #1593
Opened 2020-09-25 19:38 UTC by 3xtr4t3rr3str14l

resolves #1584

2020-09-25 21:38 UTC, 3xtr4t3rr3str14l commented
putting this here to announce my desire to skip the codeclimate check this time.  open to objections or other opinions, but just wanna make that known.

2020-09-26 06:18 UTC, dapplion commented
> putting this here to announce my desire to skip the codeclimate check this time. what it's suggesting doesn't seem necessary because it would be good to be able to look at each testnet's config in whole (without having to reference some external common objects, like they suggest with the logger params). open to objections or other opinions, but just wanna make that known.

Yeah I'm okay too with the testnet config containing duplicate code.

2020-09-26 06:21 UTC, dapplion requested changes, later dismissed

2020-09-26 06:21 UTC, dapplion commented on packages/lodestar-cli/src/testnets/index.ts
> +      return ""; // TODO: add genesis.ssz file here
Better to return null than an empty string

2020-09-27 01:22 UTC, wemeetagain approved these changes

2020-09-27 02:31 UTC, merged