removed eslint warnings from chain module
ChainSafe/lodestar pull request #221
Opened 2019-05-22 20:31 UTC by sadiq1971

2019-05-22 20:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=221) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=221) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=221) it.</sub>

2019-05-22 22:20 UTC, GregTheGreek commented
hi @sadiq1971 thanks for the PR!

Looks like you have a bit of a merge conflict, could you check that out :)

2019-05-22 23:38 UTC, sadiq1971 commented
> hi @sadiq1971 thanks for the PR!
> 
> Looks like you have a bit of a merge conflict, could you check that out :)

Hi @GregTheGreek , I have resolved the conflict. Take a look.

2019-05-22 23:56 UTC, wemeetagain requested changes
You can remove the unused import statements
Other than that looks good!

2019-05-23 00:04 UTC, GregTheGreek requested changes

2019-05-23 00:04 UTC, GregTheGreek commented on src/chain/index.ts
> +  public async initializeChain(genesisTime: number64, genesisDeposits: Deposit[]
I'd prefer if everything was on its own line for constructors
```suggestion
  public async initializeChain(
    genesisTime: number64, 
    genesisDeposits: Deposit[],
```

2019-05-23 00:04 UTC, GregTheGreek commented on src/chain/index.ts
> +    , genesisEth1Data: Eth1Data): Promise<void> {
```suggestion
    genesisEth1Data: Eth1Data): Promise<void> {
```

2019-05-23 11:41 UTC, sadiq1971 commented
It seems some new file have been added to the master branch in the previous PR . So after resolving conflict i am having error in my local branch. So I am closing this PR and Opening a Updated PR

2019-05-23 11:41 UTC, closed without merging