eslint warnings removed from eth1 module
ChainSafe/lodestar pull request #229
Opened 2019-05-24 20:07 UTC by sadiq1971

2019-05-25 21:46 UTC, GregTheGreek requested changes

2019-05-25 21:46 UTC, GregTheGreek commented on src/eth1/wallet.ts
> +    //TODO: Implement real deposit arguments according to spec :
we can remove this

2019-05-27 15:41 UTC, GregTheGreek requested changes

2019-05-27 15:41 UTC, GregTheGreek commented on src/eth1/wallet.ts
> +    // eslint-disable-next-line max-len
and this

2019-05-28 13:33 UTC, wemeetagain commented on src/eth1/defaults.ts
> +
We should probably just keep the abi and bytecode on one line.

2019-05-28 19:18 UTC, sadiq1971 commented
I have added a new commit updating with master branch and accepting your comments

2019-05-28 19:58 UTC, wemeetagain approved these changes

2019-05-29 18:46 UTC, GregTheGreek approved these changes

2019-05-29 18:47 UTC, merged