getPreState: get parent state from cache for checkpoint block to save…
ChainSafe/lodestar pull request #2385
Opened 2021-04-16 01:33 UTC by tuyennhv

… 1 epoch transiton

**Motivation**

Reduce 1 epoch transition when the node is synced.
+ we receive a gossip block at start of an epoch and we have to do epoch transition to check block proposer https://github.com/ChainSafe/lodestar/blob/5ed277e2005484b0c8e77a2e2857d501d5b938c5/packages/lodestar/src/chain/validation/block.ts#L59
+ then we do regular `runStateTransition()` which process slots (and epoch) and block inside `beacon-state-transition` module https://github.com/ChainSafe/lodestar/blob/5ed277e2005484b0c8e77a2e2857d501d5b938c5/packages/lodestar/src/chain/blocks/stateTransition.ts#L124

**Description**

Closes #2382

**Tested with prater synced node**

After processing epoch to validate gossip block, we only need to do `processSlot` inside `stateTransition`
<img width="1294" alt="Screen Shot 2021-04-16 at 08 31 06" src="https://user-images.githubusercontent.com/10568965/114958931-37952d00-9e8e-11eb-907f-9c4c284db85b.png">
[01416_server_prater_synced.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6321922/01416_server_prater_synced.cpuprofile.zip)

2021-04-16 14:13 UTC, dapplion commented on packages/lodestar/src/chain/regen/regen.ts
> +        return checkpointState;
If this both branches execute the same code could you re-org as
```ts
if (
  // Explain condition 1
  condition1 ||
  // Explain condition 2
  condition2
) {
  // Common code
}
```

2021-04-19 00:20 UTC, tuyennhv commented
with this improvement, our validator was able to publish some attestations (currently, all requests are timed out)

2021-04-19 08:25 UTC, dapplion submitted a review, later dismissed

2021-04-19 15:32 UTC, wemeetagain requested changes

2021-04-19 15:32 UTC, wemeetagain commented on packages/beacon-state-transition/src/fast/stateTransition.ts
> +      if (postState.slot < block.slot) {
This condition can be added to `processSlots` by tweaking the assertion there. eg: `assert.lte(state.slot, block.slot)`

2021-04-20 15:36 UTC, wemeetagain approved these changes

2021-04-20 15:36 UTC, merged