[WIP] Beacon Config
ChainSafe/lodestar pull request #286
Opened 2019-07-04 21:36 UTC by wemeetagain

Probably won't be able to finish today, but figured the bones are there for review
big wip warning

This splits types from sszTypes, splits params from constants. And adds mainnet/minimal presets for sszTypes and params. The presets are defined in a way that they won't cause any extra overhead.

In lodestar, I expect we'll be using mainnet params as defaults, overriding where necessary, and using `generateBeaconSSZTypes` to create ssz types since we can't necessarily rely on the presets.

2019-07-06 19:58 UTC, mpetrunic reviewed
So basically we would use ssz methods like:
```
hashTreeRoot(state, BeeaconState(generateBeaconSSZTypes(beaconParams), beaconParams)
```
?

Generally I think it's headed in the right direction but I have few suggestions.
- I would keep generators in same file as corresponding interfaces to ensure new people figure out they have to change them both
-  merge consolidate config PR into this, and put BeaconParams under chain config
- we should pass chain config throughout stateTransation

Why not make each generator accept BeaconParams and pass it on. 
Example:
```
export const Fork = (config: BeaconParams): SimpleContainerType => ({
  name: "Fork",
  fields: [
    ["previousVersion", bytes4(config)],
    ["currentVersion", bytes4(config)],
    ["epoch", Epoch(config)],
  ],
});
```

I think it would be less confusing. That said this example is kinda bad as those primitives might not even need config

2019-07-11 13:57 UTC, wemeetagain commented
issue #240

2019-07-11 14:28 UTC, wemeetagain commented
> So basically we would use ssz methods like:
> 
> ```
> hashTreeRoot(state, BeeaconState(generateBeaconSSZTypes(beaconParams), beaconParams)
> ```
> 
> ?

No change to the `hashTreeRoot` function, it still takes a value and a type.
eg:
```typescript
import {config} from "./src/config/presets/mainnet";
hashTreeRoot(state, config.types.BeaconState)
```

>     * I would keep generators in same file as corresponding interfaces to ensure new people figure out they have to change them both

I broke them out because I expect that we will want to publish interfaces separately from ssz types.
I still will keep the "consistency" test to ensure the ssz types match the interfaces. We only need to check that an interface/type exists for each ssz type, and not the other way around. Definitely worth adding some documentation about this though.


>     * merge consolidate config PR into this, and put BeaconParams under chain config

I'm hoping we can do this in a future PR :) I currently have the mainnet preset plumbed through, but we would want to have cli/toml file overrides which create a custom BeaconConfig.

>     * we should pass chain config throughout stateTransation

Updated the PR with the latest work, the config is now passed throughout.

> Why not make each generator accept BeaconParams and pass it on.
> Example:
> 
> ```
> export const Fork = (config: BeaconParams): SimpleContainerType => ({
>   name: "Fork",
>   fields: [
>     ["previousVersion", bytes4(config)],
>     ["currentVersion", bytes4(config)],
>     ["epoch", Epoch(config)],
>   ],
> });
> ```
> 
> I think it would be less confusing. That said this example is kinda bad as those primitives might not even need config

This would be less confusing! (though use slightly more memory by creating a new type object each time) I'll mess around with this style once I get all the tests passing again.

2019-07-12 01:25 UTC, GregTheGreek reviewed
I like whats going on here, kind of reminds me of how geth tosses around ctx throughout their code.

My only thought is why not have the BeaconConfig get passed around from the cli down, rather than imported into the respective files? I know that would be an annoying refactor itself, but I'm just curious to the though process.

2019-07-12 01:54 UTC, wemeetagain commented
> My only thought is why not have the BeaconConfig get passed around from the cli down, rather than imported into the respective files? I know that would be an annoying refactor itself, but I'm just curious to the though process.

We do this :) Right now, we're just passing in the "mainnet" BeaconConfig at the cli level, but the next step is to allow for the toml configuration file to override params and create a unique BeaconConfig based on that.

2019-07-12 01:56 UTC, GregTheGreek commented
> > My only thought is why not have the BeaconConfig get passed around from the cli down, rather than imported into the respective files? I know that would be an annoying refactor itself, but I'm just curious to the though process.
> 
> We do this :) Right now, we're just passing in the "mainnet" BeaconConfig at the cli level, but the next step is to allow for the toml configuration file to override params and create a unique BeaconConfig based on that.

oh neato, maybe im just misunderstanding but for instance here: https://github.com/ChainSafe/lodestar/blob/cayman/beacon-config/src/chain/factory/attestation/data.ts#L6 you're importing, and a lot of other places are like that too?

2019-07-12 01:58 UTC, wemeetagain commented
Thats just importing the BeaconConfig interface. Maybe we should call it IBeaconConfig?

2019-07-12 02:02 UTC, GregTheGreek commented
> Thats just importing the BeaconConfig interface. Maybe we should call it IBeaconConfig?

Oh I see, yeah please do that clears up so much confusion on my end, looks great otherwise!

+1 to abandoning my lerna branch lol

2019-07-12 07:08 UTC, mpetrunic requested changes
I think classes like BeaconNode or ValidatorNode should call `generateBeaconSSZTypes` as they will have  what presets are we using and it will make later PR with merging of params and default/preset params easier.

2019-07-12 07:08 UTC, mpetrunic commented on src/sszTypes/generators/index.ts
> +  // relies on list of typenames in dependency order
you could make allGenerators an array and iterate according to that order?

2019-07-12 07:08 UTC, mpetrunic commented on src/sszTypes/interface.ts
> +   */
what's up with comments?

2019-07-12 14:50 UTC, wemeetagain commented on src/sszTypes/generators/index.ts
> +  // relies on list of typenames in dependency order
I don't think you can rely on the order of imported items from modules. They're basically objects.
One idea I had is to split the files up into dependency groups, so the order of imported files could be used to ensure types get created in the right order.

2019-07-12 14:56 UTC, mpetrunic commented on src/sszTypes/generators/index.ts
> +  // relies on list of typenames in dependency order
I meant 
```
allGenerators = [
   misc,
  operations
]
...
and later on you would generate them in order in that array
```

2019-07-12 15:01 UTC, mpetrunic commented on src/sszTypes/generators/index.ts
> +  // relies on list of typenames in dependency order
or inside misc is order important?

2019-07-12 15:07 UTC, wemeetagain commented on src/sszTypes/generators/index.ts
> +  // relies on list of typenames in dependency order
This is what we're doing with the `typeNames` variable. It's supposed to be a list of all type names in dependency order.
If we keep the order with `typeNames`, we don't need to also keep the order of the imported generator files.
If we can make the files were split into dependency order, then we could definitely do that to make the commented area less verbose

2019-07-12 15:08 UTC, mpetrunic approved these changes

2019-07-13 21:06 UTC, GregTheGreek approved these changes
Gave it another look, i like it

2019-07-13 21:08 UTC, merged