Fix getAttesterDuties for next epoch
ChainSafe/lodestar pull request #3242
Opened 2021-09-24 03:55 UTC by tuyennhv

**Motivation**

+ When getting attester duties for current epoch, we have `notWhileSyncing()` check and it's good but not enough when validator ask for next epoch
+ For example in https://github.com/ChainSafe/lodestar/issues/3211#issuecomment-926320834, head epoch is at 41250 while validator asked for attester duties at epoch 41252, node should throw error instead of returning unreliable duties

**Description**

+ Check requested epoch vs headEpoch (instead of currentEpoch), it should be <=1
+ Closes #3211

2021-09-24 17:08 UTC, g11tech commented
just to mention @wemeetagain 's comment on the lodestar-testnet-alerts channel which might be relevant:

>You may wonder, why even allow getting duties if we're not fully synced? Well it's not always clear whether you're fully synced or not.
>In normal network conditions, yes, its easy to determine that your node is synced. Your clock ticks to the next slot, you receive and process that slot's block via gossip, your node determines that the new block is the new head of the chain.
>However when the network is degraded, for example during a long chain of skip slots, being synced looks just like being unsynced. So a node always needs to be able to handle this unsure area and ensure that their validators will be able to progress the chain even in these conditions.

in case of skipped slots, this will cause the node to freeze and not move forward at all (I guess)
duties reorg with throwing of the double vote error behavior is a valid behavior and is harmless.

2021-09-24 17:22 UTC, dapplion requested changes
This can be very dangerous is there are many skipped slots, like +64. It won't allow validators to participate anymore right? Because the head will be too far back.

2021-09-24 17:23 UTC, dapplion commented
I think that if the validator tracks the head event with dependant root this issue will be fixed much cleanly since the validator would realize in time when the re-org happens

2021-09-24 17:25 UTC, g11tech commented
> I think that if the validator tracks the head event with dependant root this issue will be fixed much cleanly since the validator would realize in time when the re-org happens

true, as long as validators dont double vote, duties reorg is much preferred behavior

2021-09-28 04:45 UTC, twoeths commented
**Update**
1. Only change validator, keep the node as is. Right now validator only detect duties reorg passively
2. We want to track duties reorg actively through ChainHeadTracker
  + If new head comes at the same to dependentRoot's epoch of any dutyEpoch, and the new root is different to what's the validator is tracking, and it's the last slot of an epoch => poll duties again
  + If it's not the last slot of epoch, put it to pending state. When it's 2/3 slot to the next epoch, poll duties again. (in this case, dependentRoot may not be the last slot of an epoch)
3. Refactor AttestationDutiesService to store dependent root by epoch in 2 new maps, and prune them when needed

TODOs
- [x] Test on prater (not easy to detect attesterDuties reorg but at least want to make sure it does not affect normal flow)

In my test node, I was able to catch an error like that when the node is syncing
```
Sep-28 06:56:17.478 []                 info: Found attesterDuties reorg through new head slot=1358079, dutyEpoch=42441, root=0x3ad269556b768a43571b5dfc212ed09fb056a13e3573054d008145ef94ebd8d1
Sep-28 06:56:19.665 []                 warn: Attester duties re-org. This may happen from time to time priorDependentRoot=0x816f62c55d1d95b99dcba47909fdc67e30da83c03010b58f1226dec3f165a27b, dependentRoot=0x3ad269556b768a43571b5dfc212ed09fb056a13e3573054d008145ef94ebd8d1
```

Validator works well after that

2021-09-28 11:00 UTC, g11tech approved these changes, later dismissed
just an idea or rather curiosity, why shouldn't we connect to websocket for just piping the events from bn to the connected validator processes rather than polling to bn, then validator would be more naturally processing events.

2021-09-28 11:00 UTC, g11tech commented on packages/lodestar/src/api/impl/validator/index.ts
> +      if (epoch > headEpoch + 1) {
~~ideally you should || i.e. epoch > headEpoch + 1 || epoch > chain.clock.currentEpoch + 1
in both scenarios reject api call~~
notWhileSyncing wouldn't take care of this?

2021-09-30 09:50 UTC, tuyennhv commented
need to `implement/consume previousDutyDependentRoot and currentDutyDependentRoot` in https://ethereum.github.io/beacon-APIs/#/Events/eventstream

2021-10-05 00:51 UTC, tuyennhv commented
Update: 
+ handle attester duties reorg due to the node is syncing
+ (new) handle attester duties reorg due to the head is reorg

2021-10-15 08:03 UTC, dapplion commented on packages/lodestar/src/api/impl/events/index.ts
> +      }
This is dangerous. The state is really not needed. You can figure out the dependant root only with the forkchoice. The dependant root is the parent of the target block. The `head` event argument here should already include all the data necessary

2021-10-15 08:05 UTC, dapplion commented on packages/validator/src/services/chainHeaderTracker.ts
> +
What about the reorg event? Should we subscribe to it too? Are other clients using the head + reorg events or only head?

2021-10-15 08:05 UTC, dapplion commented on packages/validator/src/services/chainHeaderTracker.ts
> +        void fn({
Better to .catch() here than void just in case

2021-10-15 08:41 UTC, dapplion commented on packages/lodestar/src/api/impl/events/index.ts
> +      }
Here these is some example code on how to compute dependant roots using the fork-choice https://github.com/ChainSafe/lodestar/blob/93a179e6fd9b64febbcf4239dccab366b215ec3f/packages/lodestar/src/chain/regen/interface.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L271

It should be improved, removing the `!` operator

2021-10-15 08:44 UTC, dapplion commented on packages/validator/src/services/attestationDuties.ts
> +  private readonly dependentRootByEpoch = new Map<Epoch, RootHex>();
I think you can merge this two data structures together using
```ts
dutiesByEpochByIndex = new Map<
  Epoch, 
  {dependantRoot: RootHex, dutiesByIndex: Map<ValidatorIndex, AttDutyAndProof>}
>();
```
Indexing by epoch -> validator should be as fast as now, and it allows faster pruning too

2021-10-15 08:45 UTC, dapplion commented on packages/validator/src/services/attestationDuties.ts
> +    if (nextTwoEpochDependentRoot && head !== nextTwoEpochDependentRoot) {
Please add a nice comment here explaining why this 3rd case is necessary, linking to the original issue that caused it. Also please add white space (1 new line) between each of the three cases

2021-10-15 09:40 UTC, twoeths commented on packages/validator/src/services/chainHeaderTracker.ts
> +
Teku handles both https://github.com/ConsenSys/teku/blob/669c608d5a5a3eae1345e8a751d3c6c1754a6e3d/validator/client/src/main/java/tech/pegasys/teku/validator/client/AbstractDutyScheduler.java#L74 (see `onChainHead()` and `onChainReorg()`)

2021-10-15 11:06 UTC, twoeths commented on packages/lodestar/src/api/impl/events/index.ts
> +      }
@dapplion forkchoice may not store the block of `compute_start_slot_at_epoch(currentEpoch - 1) - 1` because it's pruned (given the current status of https://prater.beaconcha.in/) so I have to go with getting the head state here. I think getting headState is safe enough as it should be the same data to forkchoice, let me know if you still think it's dangerous.

just check that Teku also fetch dependent root from state https://github.com/ConsenSys/teku/blob/669c608d5a5a3eae1345e8a751d3c6c1754a6e3d/storage/src/main/java/tech/pegasys/teku/storage/client/RecentChainData.java#L322

2021-10-15 13:33 UTC, dapplion commented on packages/lodestar/src/api/impl/events/index.ts
> +      }
Got it, but they don't assume that the head state will be in the cache. I understand that `retrieveStateAndBlockSummary` is sort of a regen call. I'm okay merging this now and cleaning up our regen strategy latter.

2021-10-19 04:03 UTC, twoeths commented on packages/validator/src/services/chainHeaderTracker.ts
> +
Lighthouse instead keep polling duties per slot so it does not need to handle reorg or head event.

With the mature `on_head` event api at this time, I think handling `on_head` is enough for us. As long as dependent roots are not changed, it's not necessary to poll duties again even through it's a reorg.

2021-10-19 14:23 UTC, twoeths commented
tested with a node of 4 validators, I think the performance is the same. We'll need to produce attestation data as soon as validator see new head in a separate PR.

<img width="782" alt="Screen Shot 2021-10-19 at 21 21 01" src="https://user-images.githubusercontent.com/10568965/137929773-5554b7cb-0664-4b44-a980-7d6ef77664df.png">

2021-10-25 22:26 UTC, wemeetagain commented on packages/validator/src/services/attestationDuties.ts
> +   * @returns
stray `@returns` line

2021-10-27 08:31 UTC, dapplion commented on packages/validator/src/services/attestationDuties.ts
> +    for (const validatorDuty of epochDuties.dutiesByIndex.values()) {
Add white space before for loop

2021-10-27 08:38 UTC, dapplion commented on packages/validator/src/services/attestationDuties.ts
> +    const priorDependentRoot = prior?.dependentRoot;
You can merge this lines into 
```ts
const priorDependentRoot = this.dutiesByIndexByEpoch.get(epoch)?.dependentRoot;
```
And use `priorDependentRoot` in the if statement below

2021-10-28 13:02 UTC, dapplion approved these changes

2021-10-28 13:02 UTC, dapplion commented
Awesome! :fire:

2021-10-28 13:02 UTC, merged