Updated docs for proper syntax on network.localMultiaddrs and eth1Pro…
ChainSafe/lodestar pull request #3266
Opened 2021-09-28 15:43 UTC by philknows

**Motivation**

To help clarify user docs for utilising these cli flags. Fixes #3208 

**Description**

Hard coded the proper syntax to the docs.

2021-09-28 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=3266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=3266) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=3266) it.</sub>

2021-09-28 20:28 UTC, wemeetagain approved these changes, later dismissed

2021-09-29 14:22 UTC, dapplion requested changes
We want to dynamically generate the docs with defaul values, replace JSON.Stringify for `.join(" ")`

2021-09-30 07:36 UTC, dapplion approved these changes

2021-09-30 07:37 UTC, merged