Store invalid blocks
ChainSafe/lodestar pull request #332
Opened 2019-07-18 11:55 UTC by sadiq1971

2019-07-18 13:20 UTC, mpetrunic requested changes

2019-07-18 13:20 UTC, mpetrunic commented on packages/lodestar/src/chain/chain.ts
> +      // store block root in db and terminate
add logger warn or error that you caught bad block with some info like why did it fail

2019-07-18 13:20 UTC, mpetrunic commented on packages/lodestar/src/sync/regular.ts
> +      return ;
add log of what happened, probably warn

2019-07-18 15:38 UTC, GregTheGreek requested changes

2019-07-18 15:38 UTC, GregTheGreek commented on packages/lodestar/src/db/api/beacon/beacon.ts
> +  public async isBadBlockRoot(root: bytes32): Promise<boolean> {
add whitespace

2019-07-19 04:31 UTC, mpetrunic requested changes

2019-07-19 04:31 UTC, mpetrunic commented on packages/lodestar/src/chain/chain.ts
> +      this.logger.warn( "bad block" + e.message + '\n' + e.stack);
Put as second line of catch statement, add blockroot to log, missing whitespace after "bad block", d o n' t p u t stack  th ere, you could p ri n t  stac k  asa  d ebu glog or something

2019-07-19 04:31 UTC, mpetrunic commented on packages/lodestar/src/sync/regular.ts
> +      this.logger.warn("Found bad block, skipping");
add block root to  log, this is meaningless. Format it to says "received" instead of "found"

2019-07-21 19:21 UTC, mpetrunic approved these changes

2019-07-21 19:52 UTC, GregTheGreek approved these changes

2019-07-22 06:49 UTC, merged