“L” + “GPL” Day
ChainSafe/lodestar pull request #337
Opened 2019-07-18 21:49 UTC by GregTheGreek

See ya later GPL
![GIF](https://media.giphy.com/media/3o6ZsSPYlpTX1wusGQ/giphy.gif)

2019-07-18 21:59 UTC, wemeetagain requested changes
Can you also change packages/lodestar/LICENSE?

I'm expecting each package would have its own LICENSE file governing that package.
So if we bring ssz into the mix, the Apache code can live peacefully alongside the LGPL code.

2019-07-18 22:01 UTC, GregTheGreek commented
> Can you also change packages/lodestar/LICENSE?
> 
> I'm expecting each package would have its own LICENSE file governing that package.
> So if we bring ssz into the mix, the Apache code can live peacefully alongside the LGPL code.

Actually  now that you bring that ups a good point, do we make it in the root or in each sub package?

2019-07-19 07:25 UTC, mpetrunic approved these changes

2019-07-19 21:21 UTC, wemeetagain approved these changes

2019-07-19 21:21 UTC, merged