Precompute epoch transition
ChainSafe/lodestar pull request #3383
Opened 2021-10-21 11:08 UTC by tuyennhv

**Motivation**

+ We want to have early epoch transition when the node is synced

**Description**

+ 1/3 slot before epoch boundary, run epoch transition
Closes #3382

**Test**
+ "Gossip Block" metrics in contabo-1 shows good result
<img width="1586" alt="Screen Shot 2021-10-21 at 18 08 02" src="https://user-images.githubusercontent.com/10568965/138265622-e0666757-4cfc-4e3b-9d70-25e01e3f8e62.png">

2021-10-22 07:35 UTC, g11tech submitted a review, later dismissed

2021-10-25 22:12 UTC, wemeetagain commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +      this.logger.verbose("No need to precompute epoch transition", {nextEpoch, headSlot, slot: clockSlot});
Maybe these loggers should be debug level

2021-10-26 23:11 UTC, wemeetagain submitted a review, later dismissed
lgtm

2021-10-28 03:42 UTC, twoeths commented
Tested this for a while:
+ Majority of blocks could be processed <=3s after slot starts, the main reason block is processed after 1/3 slot is due to the gossip block received late
<img width="1602" alt="Screen Shot 2021-10-28 at 10 39 08" src="https://user-images.githubusercontent.com/10568965/139182663-efa5f0c3-1294-4186-ab73-310256e064d7.png">

2021-10-28 09:07 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +      this.logger.debug("No need to precompute epoch transition", {nextEpoch, headSlot, slot: clockSlot});
When logging think that this logs are burried in a sea of information thus need content. For example
```
Skipping PrecomputeEpochScheduler node is syncing
```

2021-10-28 09:08 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.logger.verbose("Precompute epoch transition", {nextEpoch, headSlot, nextSlot});
Log `Running PrecomputeEpochScheduler`

2021-10-28 09:09 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.chain.regen.getBlockSlotState(blockRoot, nextSlot, RegenCaller.preComputeEpoch).catch((e) => {
Log both .then() `Completed PrecomputeEpochScheduler` and catch `Error on PrecomputeEpochScheduler`

2021-10-28 09:10 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.chain.regen.getBlockSlotState(blockRoot, nextSlot, RegenCaller.preComputeEpoch).catch((e) => {
Add basic metrics:
- counter metric for total PrecomputeEpochScheduler runs
- counter metric for total PrecomputeEpochScheduler errors

2021-10-28 09:11 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.chain.regen.getBlockSlotState(blockRoot, nextSlot, RegenCaller.preComputeEpoch).catch((e) => {
Another super important metric but harder to implement would to answer the question
- When does the result of this `getBlockSlotState()` epoch transition goes to waste? For that we could track re-orgs and check if the epoch transition got re-org-ed out. Also, if the last block of the epoch came very late it won't technically trigger a re-org but it would invalidate this epoch transition run.

2021-10-28 09:14 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.chain.regen.getBlockSlotState(blockRoot, nextSlot, RegenCaller.preComputeEpoch).catch((e) => {
You should also add a nice long comment on top `getBlockSlotState` call explaining what assumptions this `PrecomputeEpochScheduler` class does on the regen such that the resulting checkpoint state is cached. Also might be worth to add a test, to prevent regressions

2021-10-29 09:38 UTC, twoeths commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +    this.chain.regen.getBlockSlotState(blockRoot, nextSlot, RegenCaller.preComputeEpoch).catch((e) => {
>  Also, if the last block of the epoch came very late it won't technically trigger a re-org but it would invalidate this epoch transition run.

@dapplion in that case we skip the PreComputeEpoch task, no waste epoch transition here

> When does the result of this getBlockSlotState() epoch transition goes to waste

when noone uses the cached checkpoint, added `preComputedCheckpoint` to `CheckpointStateCache` in order to have that metric

2021-10-29 10:36 UTC, twoeths commented
New precompute epoch metrics:
+ Success vs Error vs Skip (no data for Error/Skip legend so it doesn not show)
+ Checkpoint state cache hits vs waste
<img width="1610" alt="Screen Shot 2021-10-29 at 17 33 44" src="https://user-images.githubusercontent.com/10568965/139420533-252b7bf4-4b6a-45ae-908b-3f56f6e2f5fb.png">

2021-10-29 11:13 UTC, dapplion commented on packages/lodestar/src/metrics/metrics/lodestar.ts
> +    preComputeEpoch: {
The name `preComputeEpoch` is bit too generic could we do `precomputeNextEpochTransition`? If sounds good please rename files and classes on all the PR

2021-10-29 11:14 UTC, dapplion commented on packages/lodestar/src/metrics/metrics/lodestar.ts
> +        name: "precompute_epoch_result",
See https://github.com/ChainSafe/lodestar/issues/3399

2021-10-29 11:15 UTC, dapplion commented on packages/lodestar/src/metrics/metrics/lodestar.ts
> +        help: "Number of precompute epoch skip/success/error",
Total number of precomputeNextEpochTransition runs by result

2021-10-29 11:20 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +        const previousHits = this.chain.checkpointStateCache.updatePreComputedCheckpoint(blockRoot, nextEpoch);
Can you find a a way to track this without adding custom code in the checkpointStateCache? Ideally this class should have sufficient info to know if the previous run was re-orged or not.

2021-10-29 12:27 UTC, twoeths commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +        const previousHits = this.chain.checkpointStateCache.updatePreComputedCheckpoint(blockRoot, nextEpoch);
@dapplion even when our node is reorged, it does not mean the pre computed epoch transition is wasteful as some nodes can still send attestations with our old/obsolete target checkpoint and we still need that cached target checkpoint. So for this `waste` metric, it does not depend on the node being re-orged or not, it depends on the produced checkpoint state is used or not.

2021-10-30 06:32 UTC, dapplion commented on packages/lodestar/src/chain/precomputeEpoch.ts
> +        const previousHits = this.chain.checkpointStateCache.updatePreComputedCheckpoint(blockRoot, nextEpoch);
Yeah, that's true. Let's leave it like this then

2021-11-03 15:49 UTC, wemeetagain requested changes
Can you make the naming consistent?
Either precompute or preCompute, not both

Other than that lgtm

2021-11-04 14:00 UTC, wemeetagain approved these changes

2021-11-04 14:14 UTC, dapplion approved these changes

2021-11-04 14:15 UTC, merged