backfill sync from an anchor checkpoint state
ChainSafe/lodestar pull request #3384
Opened 2021-10-21 14:25 UTC by g11tech

**Motivation**
This PR is to backfill in a scenario when wss checkpoint or any other anchor state is used to start the beacon node.

**Description**
Right now, this PR rebases https://github.com/ChainSafe/lodestar/pull/2637 on current master, making it workable base to build on top of the mentioned previous PR

Fixes:
- [x]  Don't reject the entire syncrange sequence if a block in mid is missing making it a non linear
- [x] Fixe the scenario where the syncrange keeps on resulting in a non anchored block at the end, i.e. end block is orphaned, and the previous head could be multi blocks behind, likely scenario in reorgs. Resolution, load the previous head in a solo request to set it as a new anchor
- [x] before rangeSync or sync from outside, check the DB as DB could have had blocks saved from previous run, no need to verify their signatures and blocks in db should already be verified.
- [x] Do a checkpoint check if a wss checkpoint has been provided which was in the past from the initialized beacon state (from DB because of a previous run). In case not provided compare against genesis when at genesis and panic if not same.
*Created a backfilledSequences repository module, which tracks backfilled sequences like 384:key=> 211:value i.e. backfilled  from slot 384 to 211 both including, in normal operation will typically store two sequences, one used by the backfill process and one used by the forward moving chain (which will upon finalizing will write a new sequence finalizedSlot=>chainStarted/anchorSlot). Any gaps in the db because of restarting with checkpoint sync will result into a new sequence entry, but the previous entry will be eliminated when the backfill syncs up the gap*
- [x] Strategy to skip already filled sequence (needs a strategy to track gaps or filled sequences)
- [x]  `InvalidWSCheckpoint` error (https://github.com/ChainSafe/lodestar/issues/3385)
- [x] Schedule the processing/verification when the chain is supposedly free *throttling chain by `BATCH_SIZE` in a single trigger cycle (in db reads or syncRange fetches)*
- [x] grafana dashboard

~~skipBackFillSync option?
backfillTill:  options i) till  wsCheckpoint  to be validated, ii)till GENESIS_SLOT (default) iii)till provided Slot~~

Tested Scenarios:
- [x] sync test case: sync/wss.test.ts
![image](https://user-images.githubusercontent.com/76567250/139856934-b03f4123-bd06-4281-b6e0-545b7bc7df12.png)
- [x] prater backfill sync to genesis (despite multiple restarts interrupting the sync, recovering using backfilled Sequences)
![image](https://user-images.githubusercontent.com/76567250/140637070-f9fa1aa6-d606-406a-bba1-d602f78fb007.png)
- [x] stopping and starting multiple times creating gaps in the back filled sequences, backfiled sync filled the gaps and combined them with backfilled sequences to avoid redoing previous backfill sync. 
*example of backfillSync  recovering on a restart using previous backfilled sequence (jumped back from `1633696` to `1437564`, and then continuing backfilling from there on*:
![image](https://user-images.githubusercontent.com/76567250/140506947-69559d24-c125-4861-88e6-6a3183ec2f44.png)
- [x] recovering from a persistent non anchored sequence in range sync (because of the orphaned block being served at the edge of range sync)
![image](https://user-images.githubusercontent.com/76567250/139057097-0cb8f4a4-7df7-4230-8208-9e75ddcb297c.png)
- [x] recovering the **backfilled to genesis** state on a fully backfilled node restart
![image](https://user-images.githubusercontent.com/76567250/140637382-d7757dfd-7e19-4f16-aa63-cee755dce2b9.png)
- [x] stopped a fully backfilled node and restarted after a gap with new recent checkpoint - backfilled from the new recent checkpoint to previous finalized checkpoint when the node was stopped, and then correlated with already backfilled sequence till the GENESIS to switch to backfilled complete state
![image](https://user-images.githubusercontent.com/76567250/140639596-5a20d4fa-341d-4c6f-94fc-35f9fc453110.png)

Closes #2556

2021-11-05 11:58 UTC, g11tech commented
example of backfillSync  recovering using previous backfilled sequence (jumped back from `1633696` to `1437564`, and then continuing backfilling from there on:

![image](https://user-images.githubusercontent.com/76567250/140506947-69559d24-c125-4861-88e6-6a3183ec2f44.png)

2021-11-09 07:19 UTC, dapplion commented on packages/lodestar/src/metrics/metrics/lodestar.ts
> +        name: "lodestar__backfill_sync_total_blocks",
Remove double underscore from `lodestar__backfill`

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/node/notifier.ts
> +      // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
Don't disable this rule, use strict comparisions even if it's more verbose

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/node/notifier.ts
> +            ...backfilledStat,
I won't add any info to the notifier. Users don't really care about backfill status. We must ensure it works and they trust us that it does. We should use metrics and API debug endpoints to learn about the status of backfill sync

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/backfill.ts
> +  // At any given point, we should have either the anchorBlock, or anchorBlockRoot, the reversed head of the backfill sync, from where we need to backfill
Limit line width to strictly less than 120 characters wide for readability

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/backfill.ts
> +      // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
Please remove all disablings of the rule `@typescript-eslint/strict-boolean-expressions` from this PR

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/backfill.ts
> +  private async sync(): Promise<Slot> {
This function is 134 lines long and very hard to follow, please
- Add code comments throughout the code blocks explaining what is going on and how this is intended to work
- If possible try to modularize the code with good abstractions that help the above point self-documenting the code
- As bonus (if applicable) you can add a diagram or summary of the entire flow at the top of the function

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/errors.ts
> +  // fetched blocks are not linear
Make all these comments JSDocs
```ts
/** fetched blocks are not linear */
```

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/verify.ts
> +  for (const block of blocks.slice(0).reverse()) {
Just loop backwards (with a regular for loop) without allocating a new array twice

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/backfill/verify.ts
> +    .map((block) => allForks.getProposerSignatureSet(state, block));
.filter and .map can be merged into a single loop to prevent looping twice

2021-11-09 07:46 UTC, dapplion commented on packages/lodestar/src/sync/sync.ts
> +  private readonly processingRoots = new Set<string>();
Is this used?

2021-11-09 09:02 UTC, g11tech commented on packages/lodestar/src/sync/sync.ts
> +  private readonly processingRoots = new Set<string>();
nope, will remove this :+1:

2021-11-30 08:06 UTC, dapplion commented
@g11tech Remember to mark as "Ready for review" when appropiate! Draft PRs should be a transient state for unfinished work

2021-11-30 11:09 UTC, g11tech commented
Graphana dashboard:
![image](https://user-images.githubusercontent.com/76567250/144036689-834d2e31-0b6e-4787-9d13-1aade3708264.png)

2021-11-30 11:27 UTC, dapplion commented
This looks super good! Thank you so much for the detailed charts and progression :heart: Will do another review in depth asap and should be good to go.

2021-11-30 11:36 UTC, g11tech commented
> This looks super good! Thank you so much for the detailed charts and progression heart Will do another review in depth asap and should be good to go.

thank you! :+1:

2021-12-06 17:56 UTC, wemeetagain requested changes

2021-12-06 17:56 UTC, wemeetagain commented on packages/lodestar/src/chain/interface.ts
> +  readonly anchorSlot: Slot;
would be nice to have a js doc:

Something like:
The initial slot that the chain is started with.

2021-12-06 17:56 UTC, wemeetagain commented on packages/lodestar/src/db/beacon.ts
> +  backfilledSequences: BackfilledSequences;
I think using the term "ranges" would be more descriptive than "sequences".

2021-12-07 17:29 UTC, wemeetagain requested changes, later dismissed

2021-12-07 17:29 UTC, wemeetagain commented on packages/cli/src/cmds/beacon/initBeaconState.ts
> +      await initStateFromAnchorState(config, db, logger, anchorState);
I think we should be returning the return value of initStateFromAnchorState here

2021-12-07 17:44 UTC, g11tech commented on packages/cli/src/cmds/beacon/initBeaconState.ts
> +      await initStateFromAnchorState(config, db, logger, anchorState);
`initStateFromAnchorState` returns anchorState itself, but yes it would look cleaner

2021-12-25 16:39 UTC, g11tech commented
synopsis of a test run with the latest PR code:

![image](https://user-images.githubusercontent.com/76567250/147389470-dedd73a4-6662-4ab7-85a6-c70b42ab0d22.png)
1. Started backfill sync around 16:30
2. Restarted coouple of times between ~17:00-18:30, sync recovered the previous progress using backfillRanges
3. Synced to genesis at 20:00 but sync aborted with failiure as code was checking signature of genesis block as well
4. Fixed it around 22:00, and the sync recovered previous progress to genesis which it complete successfully

@dapplion : Kindly review and let know if anything further needs to be fine tuned.

2022-01-03 10:16 UTC, g11tech commented
@dapplion updated the PR with the discussed changes (and rebased with current master). test run where backfill sync recovered previous progress and completed sync to genesis. :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/76567250/147919472-dea75ada-b9c8-414c-acad-1b428e58b422.png)

2022-01-06 17:22 UTC, dapplion approved these changes
Excellent! Looking forward to many more like this in 2022 :tada:

2022-01-06 17:25 UTC, g11tech commented
> Excellent! Looking forward to many more like this in 2022 tada

Thank you! lodestar rocks! :rocket: 
latest run on prater
![image](https://user-images.githubusercontent.com/76567250/148424342-81f22723-0482-4138-bfd3-0a1dc92e84fb.png)

2022-01-06 17:32 UTC, merged