Update README.md
ChainSafe/lodestar pull request #341
Opened 2019-07-23 18:27 UTC by ColinSchwarz

Changed link from gitter to discord

2019-07-23 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=341) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=341) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=341) it.</sub>

2019-07-23 18:30 UTC, GregTheGreek submitted a review, later dismissed

2019-07-23 19:21 UTC, mpetrunic requested changes
change badge as well

2019-07-23 19:23 UTC, GregTheGreek commented
> change badge as well

@ColinSchwarz here https://github.com/ChainSafe/lodestar/pull/341/files#diff-04c6e90faac2675aa89e2176d2eec7d8R14

2019-07-23 21:58 UTC, Mikerah submitted a review, later dismissed

2019-07-24 16:30 UTC, mpetrunic approved these changes

2019-07-24 17:48 UTC, GregTheGreek approved these changes

2019-07-24 17:49 UTC, merged