Categorize peer by agent version
ChainSafe/lodestar pull request #3472
Opened 2021-12-02 09:05 UTC by tuyennhv

**Motivation**

+ Categorize peer by agent version

2021-12-02 12:43 UTC, dapplion requested changes
We should only log the known ClientKind enum
```
Dec-02 16:00:53.413 [NETWORK]         debug: Resp sending chunk method=metadata, client=Teku, peer=16...yhBjgf, requestId=146
```

2021-12-03 07:07 UTC, wemeetagain approved these changes, later dismissed

2021-12-03 09:56 UTC, dapplion commented on packages/lodestar/src/network/peers/client.ts
> +  const agentSplit = agentVersion.split("/");
split has to manipulate the string more than necessary. If we only care about the ClientKind split the string once with
```ts
const slashIndex = agentVersion.indexOf("/")
const agentKind = slashIndex >= 0 ? agentVersion.slice(0, slashIndex) : null
```
Then return `ClientKind`

2021-12-06 07:12 UTC, dapplion approved these changes

2021-12-06 07:13 UTC, merged