Add gossip peer score metric
ChainSafe/lodestar pull request #3556
Opened 2021-12-28 09:17 UTC by tuyennhv

**Motivation**

We want to know gossip peer score in order to investigate different gossip issues

**Description**

Part of #3555

2021-12-28 19:00 UTC, dapplion commented on packages/lodestar/src/metrics/metrics/lodestar.ts
> +    },
The label peer has too much cardinality (too many different values) and will break our metrics. Refer to https://www.robustperception.io/cardinality-is-key as example on rationale.

What we want to know is an idea of the peer's score overall, not per peer specifically. You should use the `AvgMinMax` metric and dump an array of scores on each scrape

2021-12-28 19:00 UTC, dapplion requested changes
The label peer has too much cardinality (too many different values) and will break our metrics. Refer to https://www.robustperception.io/cardinality-is-key as example on rationale.

What we want to know is an idea of the peer's score overall, not per peer specifically. You should use the `AvgMinMax` metric and dump an array of scores on each scrape

2021-12-29 02:08 UTC, tuyennhv commented
> The label peer has too much cardinality (too many different values) and will break our metrics. Refer to https://www.robustperception.io/cardinality-is-key as example on rationale.
> 
> What we want to know is an idea of the peer's score overall, not per peer specifically. You should use the `AvgMinMax` metric and dump an array of scores on each scrape

thanks for the guide, in the gossip case I'd like to know number of peers in each threshold:

```ts
export const gossipScoreThresholds: PeerScoreThresholds = {
  meshThreshold: 0,
  gossipThreshold: -4000,
  publishThreshold: -8000,
  graylistThreshold: -16000,
};
```
so I'd create a new Bucket metric for this purpose so that we can reuse later.

@dapplion please let me know if there's a better way to do it

2021-12-29 04:21 UTC, tuyennhv commented
the generated metric looks like this
<img width="1258" alt="Screen Shot 2021-12-29 at 11 20 50" src="https://user-images.githubusercontent.com/10568965/147627131-3fbb9f63-9ff3-4dea-a3fb-d3f800734f31.png">

2021-12-29 18:23 UTC, dapplion commented on packages/lodestar/src/network/gossip/gossipsub.ts
> +    metrics.gossipPeer.score.set(gossipScore);
I think you can achieve the same results with regular Gauges, without a new metric type

```ts
    let peerCountScoreGraylist = 0;
    let peerCountScorePublish = 0;
    let peerCountScoreGossip = 0;
    let peerCountScoreMesh = 0;
    for (const peerIdStr of this.peers.keys()) {
      const score = this.score.score(peerIdStr);
      if (score > gossipScoreThresholds.graylistThreshold) peerCountScoreGraylist++;
      if (score > gossipScoreThresholds.publishThreshold) peerCountScorePublish++;
      if (score > gossipScoreThresholds.gossipThreshold) peerCountScoreGossip++;
      if (score > 0) peerCountScoreMesh++;
    }
    metrics.gossipPeer.scoreByThreshold.set({threshold: "graylist"}, peerCountScoreGraylist);
    metrics.gossipPeer.scoreByThreshold.set({threshold: "publish"}, peerCountScorePublish);
    metrics.gossipPeer.scoreByThreshold.set({threshold: "gossip"}, peerCountScoreGossip);
    metrics.gossipPeer.scoreByThreshold.set({threshold: "mesh"}, peerCountScoreMesh);
```

2021-12-29 18:23 UTC, dapplion commented on packages/lodestar/src/network/gossip/gossipsub.ts
> +    metrics.gossipPeer.score.set(gossipScore);
We should also track the AvgMinMax of all scores, to answer to different questions:
- `scoreByThreshold` label by threshold: How many peers are in each gossip score threshold?
- `score` AvgMinMax: How well or bad scored are the peers numerically?

2021-12-31 08:57 UTC, dapplion approved these changes

2021-12-31 09:00 UTC, merged