Use LinkedList for JobItemQueue
ChainSafe/lodestar pull request #3738
Opened 2022-02-10 06:34 UTC by tuyennhv

**Motivation**

As shown in #3732, it takes up to 17% of cpu time just to do the `array.shift()`

**Description**

+ Since we don't need random access in the `jobs` array, write a LinkedList to improve the performance
+ The benchmark shows that it's way faster to use LinkedList to do shift / push /pop
```
LinkedList vs Regular Array
    ✓ array of 16000 items push then shift                                276390.5 ops/s    3.618070 us/op   x1.140       1017 runs   5.29 s
    ✓ LinkedList of 16000 items push then shift                        7.052684e+7 ops/s    14.17900 ns/op   x0.955       8744 runs   1.73 s
    ✓ array of 16000 items push then pop                                   6606896 ops/s    151.3570 ns/op   x0.947       1720 runs   3.04 s
    ✓ LinkedList of 16000 items push then pop                          7.412898e+7 ops/s    13.49000 ns/op   x1.006       8163 runs   1.82 s
    ✓ array of 24000 items push then shift                                167710.8 ops/s    5.962646 us/op   x0.994        389 runs   3.62 s
    ✓ LinkedList of 24000 items push then shift                        7.102777e+7 ops/s    14.07900 ns/op   x0.914       2824 runs   1.16 s
    ✓ array of 24000 items push then pop                                   4541347 ops/s    220.1990 ns/op   x1.180        525 runs   3.18 s
    ✓ LinkedList of 24000 items push then pop                          7.258474e+7 ops/s    13.77700 ns/op   x1.023       4409 runs   1.65 s
```
part of #3732

2022-02-10 10:11 UTC, dapplion commented
Looks overall! @tuyennhv have you been able to test this in a beacon node?

2022-02-10 10:46 UTC, twoeths commented
> Looks overall! @tuyennhv have you been able to test this in a beacon node?

I've run it 7h in hetzner-test1 http://contabo-metrics:3000/d/lodestar/lodestar?orgId=1&var-ByJob=instance%7C%3D%7Chetzner-test1&from=now-24h&to=now&refresh=30s

at least we can maintain good number of peers there, profiles show that we don't take time for that `this.jobs.shift()` code anymore

some gossip blocks still come late, I suppose there are some validators in prater network publish late blocks (tried with v0.33.0 and it's the same)

2022-02-10 14:37 UTC, dapplion commented
@tuyennhv I would like to understand better first how often does master calls .shift(). Looking at your benchmarks the most expensive .shift() takes ~6us, so to take 17% of total CPU time

```
1e6 us/s * 0.17 / 5.9 us/op = 28813 ops/s
```

This number is absurdly high, maybe there's some other issue on top of the .shift inefficiency?

2022-02-11 02:08 UTC, tuyennhv commented
> @tuyennhv I would like to understand better first how often does master calls .shift(). Looking at your benchmarks the most expensive .shift() takes ~6us, so to take 17% of total CPU time
> 
> ```
> 1e6 us/s * 0.17 / 5.9 us/op = 28813 ops/s
> ```
> 
> This number is absurdly high, maybe there's some other issue on top of the .shift inefficiency?

@dapplion  I'm not sure how the profiler calculate the cpu percentage, maybe it's calculate against the total time for nodejs (not the total time to run profiler). From the profile, total time is 275100ms, time for `jobs.shift` is 7066ms so the ratio per total time is 2.57% (not 17%)

```
1e6 us/s * 0.0257 / 5.9 us/ops = 4353 ops/s
```

given 275_000 active validators in prater, attestation messages per second would be: `275_000/32/12 = 716 msg/s`

`4353 / 716 ~ 6` => due to gossip message redundancy, for each attestation there is approximately 6 duplicate instances. (We did not calculate gossip blocks, aggregated attestations, sync committee messages so the duplicate messages should be less than that)

2022-02-11 21:53 UTC, wemeetagain requested changes
LGTM, minor comment

2022-02-11 21:53 UTC, wemeetagain commented on packages/lodestar/src/util/array.ts
> +  prune(): void {
Can we name this `clear`?

2022-02-13 16:32 UTC, wemeetagain approved these changes

2022-02-14 19:01 UTC, merged