Observe attestation submission after the api called
ChainSafe/lodestar pull request #4010
Opened 2022-05-11 07:54 UTC by tuyennhv

**Motivation**

We want to monitor the delay time from 1/3 slot to the time attestation is published

**Description**

+ as shown in #4009, sometimes beacon node has i/o lag so we'd like to track `attesterStepCallPublishAttestation` metric after the attestation is published

part of #4009

2022-05-11 14:51 UTC, wemeetagain reviewed
Do we still want the observation before calling publishing attestations?
Should the name of this metric be changed? eg: attesterStepFinishPublishAttestation or something

2022-05-12 01:58 UTC, dapplion requested changes

2022-05-12 01:58 UTC, dapplion commented on packages/validator/src/services/attestation.ts
> +      this.metrics?.attesterStepCallPublishAttestation.observe(this.clock.secFromSlot(slot + 1 / 3));
Agree with @wemeetagain the metric name clearly states "before call to publish attestation". You can already get the metric you want by summing `attesterStepCallPublishAttestation + vc rest request time {routeId=submitPoolAttestations}`.

If you want to be more granular metrics, those should be added in the beacon chain not here

2022-05-12 02:08 UTC, dapplion commented on packages/validator/src/services/attestation.ts
> +      this.metrics?.attesterStepCallPublishAttestation.observe(this.clock.secFromSlot(slot + 1 / 3));
If your goal is to measure how busy the beacon node is (potentially due to i/o lag), just use the api request time metric

2022-05-16 13:43 UTC, wemeetagain commented
@tuyennhv

Are you able to measure what you want using the API request time metric?
Can we close this PR?

2022-05-17 01:26 UTC, twoeths commented
> @tuyennhv
> 
> Are you able to measure what you want using the API request time metric? Can we close this PR?

yeah I'd use the API request time metric instead

2022-05-17 01:26 UTC, closed without merging