Modify gossipsub params following consensus spec v1.1.10
ChainSafe/lodestar pull request #4011
Opened 2022-05-11 08:38 UTC by tuyennhv

**Motivation**

Strictly follow consensus spec v1.1.10

**Description**

+ D params: same
+ heartbeatInterval: change from 1s to 0.7s
+ fanoutTTL: same
+ mcacheLength: change from 5 to 6
+ mcacheGossip: same
+ seenTTL: change from 5 minutes to 6.4 minutes (550 hearbeatInterval)

Closes #3865

**TODO**
- [ ] Test on feature group

2022-05-12 02:07 UTC, dapplion requested changes

2022-05-12 02:07 UTC, dapplion commented on packages/lodestar/src/network/gossip/gossipsub.ts
> +    const heartbeatInterval = 0.7 * 1000;
This should be a constant at the top in all caps, with a link to the spec page that defines it

2022-05-17 08:37 UTC, tuyennhv commented
All of the metrics are the same to master, specifically:
+ Lodestar cpu percentage (since gossipsub computeScore() may run more frequently)
+ Average gossipsub score
+ Number of mesh peer threshold

2022-05-18 03:50 UTC, dapplion approved these changes

2022-05-19 16:42 UTC, wemeetagain approved these changes

2022-05-19 16:42 UTC, merged