Assert tag in release workflow
ChainSafe/lodestar pull request #4056
Opened 2022-05-25 03:09 UTC by tuyennhv

**Motivation**

An unintended release was created because I missed `--no-git-tag-version` param when I try `lerna version` command locally

**Description**

- Release workflow should assert tag version
- Create `assert-tag.mjs` to be used for both release workflow and `release.mjs` script

Closes #4050

2022-05-25 06:02 UTC, g11tech submitted a review, later dismissed

2022-05-25 14:10 UTC, wemeetagain requested changes

2022-05-25 14:10 UTC, wemeetagain commented on .github/workflows/release.yml
> +        run: node scripts/assert_tag.mjs
I think we need something like:
```ts
node -e 'import("./scripts/assert_tag.mjs").then(({assertTag}) => assertTag())'
```

2022-05-26 03:46 UTC, dapplion commented on .github/workflows/release.yml
> +        run: node scripts/assert_tag.mjs
Why?

2022-06-01 02:08 UTC, tuyennhv commented
closing the PR as there is new release process

2022-06-01 02:08 UTC, closed without merging