Bls benchmarking and optimisation
ChainSafe/lodestar pull request #406
Opened 2019-08-28 14:39 UTC by mpetrunic

- benchmark suites for bls
- optimisation of aggregated signatures

Current suites are not really good as sample setups takes too much time, I will open issue to generate json sample cases once and always run against those sample cases.

2019-08-28 14:42 UTC, GregTheGreek submitted a review, later dismissed

2019-08-28 17:04 UTC, wemeetagain requested changes

2019-08-28 17:04 UTC, wemeetagain commented on packages/bls/src/helpers/g1point.ts
> +  public addRaW(other: bytes48): G1point {
maybe `addRaw`

2019-08-28 17:04 UTC, wemeetagain commented on packages/bls/src/index.ts
> +    console.log(e);
should this be there?

2019-08-28 18:21 UTC, mpetrunic commented on packages/bls/src/index.ts
> +    console.log(e);
probably not, accident

2019-08-31 15:34 UTC, mpetrunic commented
@GregTheGreek @wemeetagain can we merge this?

2019-08-31 15:54 UTC, GregTheGreek approved these changes

2019-09-03 19:09 UTC, mpetrunic commented
@wemeetagain this is kinda important

2019-09-03 19:14 UTC, wemeetagain approved these changes

2019-09-03 19:14 UTC, merged