Turn off the import/no-named-as-default-member in tests
ChainSafe/lodestar pull request #4162
Opened 2022-06-15 11:13 UTC by dadepo

**Motivation**

After an upgrade of eslint, it seems the rule got stricter and logs get filled with a wall of warning as shown below:

```
@chainsafe/lodestar:   12:10  warning  Caution: `sinon` also has a named export `createStubInstance`. Check if you meant to write `import {createStubInstance} from 'sinon'` instead  import/no-named-as-default-member
@chainsafe/lodestar: 
@chainsafe/lodestar: ✖ 126 problems (0 errors, 126 warnings)
@chainsafe/lodestar: 

```
This PR disables the rule that leads to these warning in test files. It can be re-enabled and warning fixed in future if it is considered to be important, but for now, removing the wall of log would be nicer.

2022-06-15 18:54 UTC, wemeetagain commented
Can you open an issue to reevaluate the rule?

2022-06-16 07:23 UTC, dapplion commented
Why not fix the warning instead of disabling?

2022-06-16 07:26 UTC, dapplion requested changes

2022-06-16 07:26 UTC, dapplion commented on .eslintrc.js
> +        "import/no-named-as-default-member": "off",
Add a comment explaining why we don't need this rule and what it does.

2022-06-21 05:52 UTC, dapplion approved these changes

2022-06-21 05:52 UTC, merged