Add logs to slashing protection import/export for better UX
ChainSafe/lodestar pull request #4257
Opened 2022-07-07 13:33 UTC by g11tech

**Motivation**
The slashing protection import/export could take a long time with user wondering if lodestar got stuck.

This PR adds better logging to the import/export via winston logger.

eg (validator pubkeys here are for kiln testnet)
### Import
```typescript
./lodestar  validator  slashing-protection import --network kiln  --rootDir /root/kiln-data/lodestar/vals495-499  --file /root/kiln-data/lodestar/spexport.json --logLevel debug
Jul-07 12:56:18.416[]                 info: Importing the slashing protection logs dbPath=/root/kiln-data/lodestar/vals495-499/validator-db
Jul-07 12:56:18.519[]              verbose: Reading the slashing protection logs file=/root/kiln-data/lodestar/spexport.json
Jul-07 12:56:19.725[]                 info: Importing logs for Validator 0x828ee58143149640384f4ddeb7fe5baa8a311ed62aa453c17c13d0c48183a36e7e74b5e26859e029705b284ff390c2bc
Jul-07 12:56:26.613[]                 info: Importing logs for Validator 0x91a09c0e67732124d3d3b51ba4b4c97f39c0b2d72b02b45d8e3f314af73d934629e66a59cb71b14c8bbe8d3722f1639f
Jul-07 12:56:34.423[]                 info: Importing logs for Validator 0xa1ee3fc1accae609c27d8edf316a45d477a24e471f73d42ec872933a5e3f92ade868c4920c4c4f613e1103d45f3ffd94
Jul-07 12:56:41.149[]                 info: Importing logs for Validator 0xa5e6aeaf0b8359854ca6de3dab48bcc1c953167a1e2c7c9c4ddbf2edcced724f21014e19e2c97ee217aaaeb1a7859320
Jul-07 12:56:48.895[]                 info: Importing logs for Validator 0xb8ab94e1f599e9afefd2e17a6e4f9cc22a3a280eb49341a5c4a5309ae60b19679eb45b5f92b75ec331d8eb49bb5f5c9d
Jul-07 12:56:57.420[]                 info: Importing logs for Validator 0x47454e455349535f54494d45
Jul-07 12:56:57.422[]                 info: Importing logs for Validator 0x47454e455349535f56414c494441544f52535f524f4f54
Jul-07 12:56:57.423[]                 info: Import completed successfully
```
### export
```typescript
./lodestar  validator  slashing-protection export --network kiln  --rootDir /root/kiln-data/lodestar/vals495-499  --file /root/kiln-data/lodestar/spexport.json --logLevel debug
Jul-07 12:44:11.752[]                 info: Extracting the slashing protection logs version=4, format=complete, dbPath=/root/kiln-data/lodestar/vals495-499/validator-db, file=/root/kiln-data/lodestar/spexport.json
Jul-07 12:44:11.851[]              verbose: Fetching the pubkeys from the slashingProtection db
Jul-07 12:44:21.076[]                 info: Starting export for pubkeys found pubkeys=7
Jul-07 12:44:21.077[]                 info: Exporting logs for Validator 0x828ee58143149640384f4ddeb7fe5baa8a311ed62aa453c17c13d0c48183a36e7e74b5e26859e029705b284ff390c2bc
Jul-07 12:44:21.400[]                 info: Exporting logs for Validator 0x91a09c0e67732124d3d3b51ba4b4c97f39c0b2d72b02b45d8e3f314af73d934629e66a59cb71b14c8bbe8d3722f1639f
Jul-07 12:44:21.640[]                 info: Exporting logs for Validator 0xa1ee3fc1accae609c27d8edf316a45d477a24e471f73d42ec872933a5e3f92ade868c4920c4c4f613e1103d45f3ffd94
Jul-07 12:44:21.898[]                 info: Exporting logs for Validator 0xa5e6aeaf0b8359854ca6de3dab48bcc1c953167a1e2c7c9c4ddbf2edcced724f21014e19e2c97ee217aaaeb1a7859320
Jul-07 12:44:22.210[]                 info: Exporting logs for Validator 0xb8ab94e1f599e9afefd2e17a6e4f9cc22a3a280eb49341a5c4a5309ae60b19679eb45b5f92b75ec331d8eb49bb5f5c9d
Jul-07 12:44:22.505[]                 info: Exporting logs for Validator 0x47454e455349535f54494d45
Jul-07 12:44:22.540[]                 info: Exporting logs for Validator 0x47454e455349535f56414c494441544f52535f524f4f54
Jul-07 12:44:22.545[]                debug: Serializing Interchange
Jul-07 12:44:23.751[]                 info: Exporting the the slashing protection logs to file
Jul-07 12:44:24.219[]              verbose: Export completed successfully
```
Closes #4184

2022-07-07 14:11 UTC, dapplion commented
@g11tech How long does the import / export of a single validator take from your tests?

2022-07-07 17:01 UTC, g11tech commented
> @g11tech How long does the import / export of a single validator take from your tests?

I tried exporting this on our kiln node with 500 dbs which has `8GB` ram, but the process got killed as it went OOM:
```typescript
Jul-07 16:33:38.807[]                 info: Extracting the slashing protection logs version=4, format=complete, dbPath=/root/kiln-data/lodestar/validator-db, file=/root/kiln-data/lodestar/spexport.json
Jul-07 16:33:38.885[]              verbose: Fetching the pubkeys from the slashingProtection db
./lodestar: line 7: 2437989 Killed                  node --trace-deprecation --max-old-space-size=4096 ./packages/cli/bin/lodestar.js "$@"
```

as per our new logs, it happened while listing pub keys from the `slashingProtection` module, it could be same issue that affected the validator decoding in the validator start that we fixed via serializing.

2022-07-18 09:27 UTC, nazarhussain requested changes, later dismissed

2022-07-18 09:27 UTC, nazarhussain commented on packages/cli/src/cmds/validator/slashingProtection/export.ts
> +    const dbPath = validatorPaths.validatorsDbDir;
```suggestion
    const {validatorsDbDir: dbPath} = getValidatorPaths(args);
```

2022-07-18 09:27 UTC, nazarhussain commented on packages/cli/src/cmds/validator/slashingProtection/import.ts
> +    const dbPath = validatorPaths.validatorsDbDir;
```suggestion
    const {validatorsDbDir: dbPath} = getValidatorPaths(args);
```

2022-07-18 13:30 UTC, wemeetagain approved these changes

2022-07-18 15:05 UTC, merged