Clean up type usage
ChainSafe/lodestar pull request #426
Opened 2019-09-03 18:54 UTC by austinabell

- Completes #356 

I believe I got all of the relevant types but I may be missing a few where the type wasn't inherently obvious. 

There was [one reference](https://github.com/ChainSafe/lodestar/compare/austin/typesusage?expand=1#diff-48aa8b885f7c3241dd71fde30288b82bR42) that I thought could be either because the eth1 deposit index would not be a validator index but could map and be used directly as one. Let me know if I should change this back or just remove the comment I added.

2019-09-03 21:41 UTC, mpetrunic requested changes

2019-09-03 21:41 UTC, mpetrunic commented on packages/eth2.0-types/src/state.ts
> +  eth1DepositIndex: ValidatorIndex; // Check this
nope, we don't have type for that, it's simple js number

2019-09-03 21:41 UTC, mpetrunic commented on packages/eth2.0-types/src/validator.ts
> +  committeeIndex: ValidatorIndex;
I think this is a bit misleading. as index in committee is different than ValidatorIndex and it will never be uint or something

2019-09-03 21:41 UTC, mpetrunic commented on packages/lodestar/src/eth1/options.ts
> +      "outputs": [{"type": "Hash", "name": "out"}],
nope, thats eth1 abi :stuck_out_tongue:

2019-09-03 22:09 UTC, austinabell commented on packages/lodestar/src/eth1/options.ts
> +      "outputs": [{"type": "Hash", "name": "out"}],
xD I assumed because name was get_hash_tree_root

2019-09-03 22:23 UTC, mpetrunic submitted a review, later dismissed

2019-09-04 04:05 UTC, GregTheGreek approved these changes

2019-09-04 05:29 UTC, mpetrunic approved these changes

2019-09-04 05:29 UTC, merged