Implement Beacon node fork rest api
ChainSafe/lodestar pull request #442
Opened 2019-09-08 07:38 UTC by tuyennhv

## Goal
+ Close #409

2019-09-08 18:57 UTC, mpetrunic requested changes

2019-09-08 18:57 UTC, mpetrunic commented on packages/lodestar/src/api/rpc/api/beacon/beacon.ts
> +    const networkId: uint64 = await this.chain.networkId;
could you create `{fork: BeaconState, chainId: number64}` in impl directory and use it from both rest and rpc so we don't have duplicate code

2019-09-08 18:57 UTC, mpetrunic commented on packages/lodestar/src/api/rpc/api/beacon/interface.ts
> +  getFork(): Promise<{fork: Fork; chain_id: uint64}>;
I would keep everything camelcase in rpc

2019-09-10 16:45 UTC, mpetrunic approved these changes

2019-09-18 09:26 UTC, mpetrunic requested changes
Also could you add test case when beacon state is null (chain didn't start)

2019-09-18 09:26 UTC, mpetrunic commented on packages/lodestar/src/api/impl/beacon/fork.ts
> +  const networkId: uint64 = await chain.networkId;
do we really need await here?

2019-09-18 09:26 UTC, mpetrunic commented on packages/lodestar/src/api/impl/beacon/fork.ts
> +  const state: BeaconState = await db.state.getLatest();
niot sure if api specifies error in case chain didn't yet started (getLatest returns null)?

2019-09-20 14:12 UTC, mpetrunic approved these changes

2019-09-20 15:07 UTC, wemeetagain approved these changes
lgtm

2019-09-20 15:08 UTC, merged