Attestation Pruning
ChainSafe/lodestar pull request #447
Opened 2019-09-08 19:14 UTC by GregTheGreek

This pr introduces attestation pruning before the opPool starts up. It removes attestations that are outside of the min and max inclusion delay

2019-09-09 14:06 UTC, mpetrunic requested changes

2019-09-09 14:06 UTC, mpetrunic commented on packages/lodestar/src/opPool/modules/attestation.ts
> +      return !isValidAttestationSlot(config, attestationSlot, state.slot)
isnt this removing attestations that are waiting for inclusion delay?

2019-09-09 14:06 UTC, mpetrunic commented on packages/lodestar/src/opPool/modules/attestation.ts
> +      return !isValidAttestationSlot(config, attestationSlot, state.slot)
and not removing ones that aren't targeting current or previous epoch?

2019-09-09 20:33 UTC, mpetrunic approved these changes

2019-09-18 09:14 UTC, mpetrunic approved these changes

2019-09-20 16:06 UTC, wemeetagain commented
I think we can close this in favor of the interop branch.
https://github.com/ChainSafe/lodestar/pull/439/files#diff-3608c095dc65cd197d70c53caeb0f243R24

2019-09-20 16:15 UTC, GregTheGreek commented
agreed

2019-09-20 16:15 UTC, closed without merging

2019-09-22 06:59 UTC, mpetrunic commented
@GregTheGreek @wemeetagain This PR is trying to merge into interop, did we ever pushed this functionality to interop branch?

2019-09-22 20:22 UTC, GregTheGreek commented
@mpetrunic there is a function called [removeOld()](https://github.com/ChainSafe/lodestar/pull/439/files#diff-3608c095dc65cd197d70c53caeb0f243R24) that got pushed :)