Increase stateCache size to fix headState missing in checkpoint sync start
ChainSafe/lodestar pull request #4534
Opened 2022-09-10 23:05 UTC by g11tech

In checkpoint sync start, the stateCache of 3 * 32 caches seem to be not sufficient since generally we start from finalized which is almost 3 epochs behind 
So before bn can sync blocks and generate more states nearer to head, the getHeadState functions seem to be running out of the states.

This PR does a quick-fix for expanding the stateCache's cache to 6 epochs (to give  margin on 3 epochs) so that bns can stay behind 3 epochs + while still trying to find/sync peers.
There could be a better solution, but this is a hotfix to the current issue users might run into.

(see the notifier crossing 96+ skipped slots here since last finalized checkpoint sync comforably without error) 
![image](https://user-images.githubusercontent.com/76567250/189504597-c749cc7f-1ebf-4d95-916c-96a35bf5b9fb.png)

User issue also seems to have resolved.

Closes #4523

2022-09-12 04:38 UTC, tuyennhv commented on packages/beacon-node/src/chain/stateCache/stateContextCache.ts
> +const MAX_STATES = 6 * 32;
we need to investigate the impact of this with regards to the heap memory (which lead to `gc` percentage metrics). In the past when chain was not finalized for a while I saw the heap memory spiked at the same time.

2022-09-12 07:50 UTC, dapplion requested changes
We must not merge this increase in cache size. The problem here is that the head state should never be dropped; period. This change will dramatically increase the change of OOM in Lodestar

2022-09-12 09:15 UTC, g11tech commented
> We must not merge this increase in cache size. The problem here is that the head state should never be dropped; period. This change will dramatically increase the change of OOM in Lodestar

let me see how we can handle this particular case in a better way

2022-09-25 11:27 UTC, g11tech commented
fixed in https://github.com/ChainSafe/lodestar/pull/4562

2022-09-25 11:27 UTC, closed without merging