Switch from Debug -> Verbose
ChainSafe/lodestar pull request #457
Opened 2019-09-12 14:59 UTC by GregTheGreek

2019-09-18 09:11 UTC, mpetrunic requested changes
This is just wrong hahah

- winston logger doesnt implement verbose and silly methods from I logger interface
- instead of custom filter, you should do:
```
createLogger({
levels: {
   levels: {
      error: 0, 
      warn: 1, 
      info: 2, 
      verbose: 3, 
      debug: 4, 
      silly: 5 
   },
  colors: {
     error: 'red',
     warn: 'yellow',
     info: 'green',
     verbose: 'cyan',
     debug: 'blue',
     silly: 'magenta'
  }
}
})
```

Although that are default values so I'm pretty sure you got weird behavior because of wrong level option supplied or missing methods

2019-09-18 09:11 UTC, mpetrunic commented on packages/lodestar/src/logger/winston.ts
> +      level: LogLevel[LogLevel.verbose], // log level switching handled in `createLogEntry`
should be just `LogLevel.verbose` or `options.level`

2019-09-18 16:20 UTC, GregTheGreek commented
@mpetrunic verbose and silly are built into the winston logger...

2019-09-18 16:27 UTC, mpetrunic commented
> @mpetrunic verbose and silly are built into the winston logger...

interface methods still not implemented though

I though you wanted to change colors on them

2019-09-18 16:28 UTC, GregTheGreek commented
> interface methods still not implemented in WinstonLogger class
Ah yes you're right I'll add those. 

> I though you wanted to change colors on them
For now, I don't see a point - adding the extra log levels should suffice for now

2019-09-18 17:09 UTC, GregTheGreek commented
updated

2019-09-20 14:10 UTC, mpetrunic approved these changes

2019-09-20 14:23 UTC, wemeetagain approved these changes

2019-09-20 14:23 UTC, wemeetagain commented on packages/lodestar/src/logger/interface.ts
> +};
love it

2019-09-20 14:23 UTC, merged