Disallow usage of console.log
ChainSafe/lodestar pull request #4585
Opened 2022-09-21 18:46 UTC by dadepo

**Motivation**

Recent changes leads to the having warnings like above when the lint task is run:

```
  lodestar git:(dadepo/fix-lint-warnings) ✗ yarn lint
yarn run v1.22.19
$ eslint --color --ext .ts packages/*/src packages/*/test

/Users/dadepoaderemi/Documents/work/chainsafe/official/lodestar/packages/cli/test/simulation/simulation.test.ts
  50:5  warning  Unexpected console statement  no-console

/~/ExternalSignerServer.ts
  61:5  warning  Unexpected console statement  no-console
  63:5  warning  Unexpected console statement  no-console
  67:5  warning  Unexpected console statement  no-console
  69:5  warning  Unexpected console statement  no-console

/~/LodestarBeaconNodeProcess.ts
  106:5  warning  Unexpected console statement  no-console
  115:5  warning  Unexpected console statement  no-console
  125:5  warning  Unexpected console statement  no-console
...
✖ 16 problems (0 errors, 16 warnings)
```

**Description**

This PR is to remove the console warnings. It does this by using `/* eslint-disable no-console */` as needed. But other solutions could be:

1. Use logging library in tests instead of console?
2. If console logging is deemed acceptable in tests, then configure it that way in the `.eslintrc` file?

If any of these two other solutions is preferred, then let me know in the comments and I can update the PR accordingly.

2022-09-23 02:56 UTC, tuyennhv submitted a review, later dismissed

2022-09-27 18:19 UTC, wemeetagain commented
I think ideally your idea 2 can be used.

2022-09-29 12:25 UTC, dapplion requested changes
IMO console.log usage is not acceptable anywhere including tests. We _may_ use it sometimes if it's really useful but usage must be discouraged in tests, and (potentially) forbidden in src code.

2022-10-02 17:48 UTC, dapplion approved these changes

2022-10-02 17:48 UTC, merged