gossip attestation validation: handle no committee error
ChainSafe/lodestar pull request #4589
Opened 2022-09-23 08:09 UTC by tuyennhv

**Motivation**

When an attestation came from an out of synced node, our logs look like:
```
Aug-11 02:29:41.278[NETWORK]         error: Gossip validation beacon_attestation threw a non-GossipActionError  Requesting slot committee out of range epoch: 113742 current: 113740
Error: Requesting slot committee out of range epoch: 113742 current: 113740
    at EpochContext.getShufflingAtEpoch (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:720:13)
    at EpochContext.getShufflingAtSlot (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:709:17)
    at getCommitteeIndices (file:///usr/app/node_modules/@lodestar/beacon-node/src/chain/validation/attestation.ts:287:56)
    at validateGossipAttestation (file:///usr/app/node_modules/@lodestar/beacon-node/src/chain/validation/attestation.ts:91:28)
    at runMicrotasks (<anonymous>)
```
Two issues here:
- the log look dangerous to the user
- we did not handle no committee error well, and we treated this case as `IGNORE` instead of `REJECT`

**Description**

- Handle the no committee scenario in gossip attestation/aggregateAndProof validation: return `REJECT` to gossipsub
- Correct log level just in case we got non-attestation errors

Closes #4396

2022-09-24 13:26 UTC, wemeetagain commented
I think the error is happening when a node hasn't been getting blocks for an epoch, but manages to publish an attestation the next epoch.

Eg: node last received block in epoch 1, publishes an attestation in epoch 3.
Then when we're verifying the attestation, we use regen to get the state at epoch 1, and can't get the shuffling for epoch 3.

In order to process the attestation, we could use `regen.getBlockSlotState` to dial the state to the right epoch.

But I don't think we should just reject, since this may be a valid attestation.

2022-09-29 02:09 UTC, tuyennhv commented
> In order to process the attestation, we could use regen.getBlockSlotState to dial the state to the right epoch.

yeah that's exactly what we did in the past, there's a performance concern with it as we may need extra epoch transition just to process an attestation, and we changed to just use the state at block which make our node more stable. The main point for this issue is just for the log

> But I don't think we should just reject, since this may be a valid attestation.

agree, we should not reject, I'll change to ignore (same behaviour to earlier too)

2022-09-29 08:48 UTC, dapplion requested changes
Instead of adding a try / catch would prefer to make getShufflingAtEpoch or a separate function return null if out of range. Then the validation code can throw the error directly if returned value is null

2022-10-03 06:51 UTC, dapplion approved these changes

2022-10-03 07:07 UTC, merged