Implement withdrawals in capella
ChainSafe/lodestar pull request #4707
Opened 2022-10-31 17:57 UTC by g11tech

Implement withdrawals in capella
WIP

2022-11-03 16:27 UTC, dapplion commented on packages/beacon-node/src/chain/produceBlock/produceBlockBody.ts
> +  seq: ForkSeq,
name variable `fork`, seq is way to generic. If there's another fork variable, then forkSeq

2022-11-03 16:28 UTC, dapplion commented on packages/beacon-node/src/chain/produceBlock/produceBlockBody.ts
> +  const withdrawals = state.withdrawalQueue.toValue();
This is very inefficient, you are reading converting an unbounded list of max length 2*40, to a value; then slicing a tiny portion. Instead create a new array and iterate what you need

2022-11-03 16:30 UTC, dapplion commented on packages/beacon-node/test/spec/utils/specTestIterator.ts
> +          ["full_withdrawals", "partial_withdrawals", "bls_to_execution_change", "withdrawals"].includes(testHandler)
Since this lists are growing large can you define constants at the top with the exclusion list or tests, forks, etc?

2022-11-03 16:57 UTC, dapplion requested changes
SSZ has some very specific un-written rules for how to use it correctly. I address them here in this video with commentary https://vimeo.com/766978569

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processBlsToExecutionChange.ts
> +    )
Set `withdrawalCredentials.slice(WITHDRAWAL_PREFIX_BYTES, 32)` and other predicate to a variable to dedup code between if and error render

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processBlsToExecutionChange.ts
> +  validator.withdrawalCredentials = withdrawalCredentials;
Please add whitespace in this function body. Before every logical group add 1 new line

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processOperations.ts
> +  if (fork >= ForkSeq.capella) {
Add 1 new line before if

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processWithdrawals.ts
> +  state.commit();
Why commit here? This will destroy performance improvements of ssz v2

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processWithdrawals.ts
> +  const withdrawalQueue = state.withdrawalQueue.toValue();
See comment above about turning the entire queue into a value

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/block/processWithdrawals.ts
> +  //Withdrawal queue has leftover
```suggestion
  // Withdrawal queue has leftover
```
Whitespace before logical groups please; here 1 new line before the comment

2022-11-03 16:57 UTC, dapplion commented on packages/state-transition/src/epoch/processWithdrawals.ts
> +      //withdraw_balance
```suggestion
      // withdraw_balance
```

2022-11-03 18:52 UTC, g11tech commented on packages/beacon-node/src/execution/engine/http.ts
> +    amount: numToQuantity(withdrawal.amount),
not to self, convert in wei (bigendian)
https://github.com/ethereum/execution-apis/pull/195/files#diff-571851156237b81c20006ce9d7a70b3421f19540cead91f45955316c52fe94c0R202

2022-11-03 18:53 UTC, g11tech commented on packages/beacon-node/src/execution/engine/http.ts
> +    amount: quantityToBigint(serialized.amount),
note to self : convert to gwei + check endianess
https://github.com/ethereum/execution-apis/pull/195/files#diff-571851156237b81c20006ce9d7a70b3421f19540cead91f45955316c52fe94c0R202

2022-11-15 11:36 UTC, g11tech commented
superseded by https://github.com/ChainSafe/lodestar/pull/4730

2022-11-15 11:36 UTC, closed without merging