Add scrape_location as default label to beacon and validator metrics
ChainSafe/lodestar pull request #4897
Opened 2022-12-11 15:06 UTC by nflaig

**Motivation**

Fixes metrics that use the `scrape_location` label and makes it independent from the deployment configuration i.e. it should not be required to set this label in prometheus configuration file which is currently also not the case, e.g. see [eth-docker lodestar jobs](https://github.com/siimon/prom-client#default-labels-segmented-by-registry).

**Description**

Adds the `scrape_location` as default label to beacon and validator node. See [prom-client default labels](https://github.com/siimon/prom-client#default-labels-segmented-by-registry) for more details.

Closes #4809

2022-12-12 11:04 UTC, dapplion requested changes
Thank you so much for the contribution!

First of all I want to help others consume our dashboards. However adding a default label to all metrics has a non-negligible cost on scrape I'm not willing to pay for given that this happens on the main thread.

Other ideas I got:
- Add labels on eth-docker setup. Metrics are purely additive and we could push for that standard to differentiate process metrics. Probably other clients have the same issue: for example for Go GC metrics
- In our dashboard set the metric to a negative (scrape_location != validator instead of scrape_location == beacon)
- Add a doc on notes on how to consume our dashboards with a list of expected labels and a proposed setup

2022-12-12 12:34 UTC, nflaig commented
> a default label to all metrics has a non-negligible cost on scrape I'm not willing to pay for given that this happens on the main thread

I already had a feeling you would say that, especially because the label is not used by a lot of dashboard metrics at the moment

> Add labels on eth-docker setup. Metrics are purely additive and we could push for that standard to differentiate process metrics. Probably other clients have the same issue: for example for Go GC metrics

I will look into this, they have specific prom config per client so it should not be a problem. Also this needs to be added to the prom config files in lodestar repository itself

> In our dashboard set the metric to a negative (scrape_location != validator instead of scrape_location == beacon)

could be a solution but I generally don't like doing this, as it would become to unspecific if there are more `scrape_location` labels in the future

> Add a doc on notes on how to consume our dashboards with a list of expected labels and a proposed setup

Definitely, will do the PR on eth-docker and then see how and where this could be documented

2022-12-12 12:34 UTC, closed without merging

2022-12-12 14:31 UTC, nflaig commented
@dapplion  just as a follow up , I quickly checked other dashboards, the [prysm dashboard](https://raw.githubusercontent.com/metanull-operator/eth2-grafana/master/eth2-grafana-dashboard-single-source-beacon_node.json) relies on the job name to differentiate the metrics. I think this is slightely better than adding another label, just need to ensure the jobs are properly named, could use the same job name `validator` and `beacon node` to use the same values as prysm.

![image](https://user-images.githubusercontent.com/38436224/207067370-8a8e84b9-7106-4549-8376-0ed3d1b779ca.png)

[Another prysm dashboard](https://raw.githubusercontent.com/ynager/grafana-eth-staking/main/dashboard.json) adds another `name` label, so even the within the different prysm dashboards there seem to be no standardization but to be fair those all come from different repositories.

![image](https://user-images.githubusercontent.com/38436224/207068532-5058b9d4-33e4-4734-82ba-5e14c9c95570.png)

2022-12-13 05:15 UTC, dapplion commented
Yeah it's a bit chaotic. I tend to base on this guides for sanity https://prometheus.io/docs/concepts/jobs_instances/ from those, what do you think is the best set of label names?

2022-12-13 08:41 UTC, nflaig commented
I think just using the existing `job` label is the most inituititve and best solution as this makes it easy for developers/operators to understand where the label is coming from. I also think it is good to have a separate job per service.

About the label values, I think calling the jobs just `beacon` and `validator` is fine and would be inline with the lodestar cli args.