Find more topic peers when subscribeAllSubnets
ChainSafe/lodestar pull request #4922
Opened 2022-12-19 06:51 UTC by tuyennhv

**Motivation**

- If we enable `subscribeAllSubnets` flag, we want the node to have some certain topic/mesh peers in each subnet, but right now we don't actively search for it

**Description**

- If we enable that flag, act like we have `ATTESTATION_SUBNET_COUNT` validators connecting to our node, i.e. actively search for nodes subscribing to requested subnets (which are all subnets in this case)
- This only happens on mainnet, on goerli I think there are a lot of peers subscribing to many/all subnets so it does not happen

Closes #4921

2022-12-19 08:23 UTC, dapplion requested changes
Why is using the randomSubscriptionSloLen() here necessary?

I think this branch should achieve the same with simpler strategy https://github.com/ChainSafe/lodestar/compare/tuyen/more_topic_peers_subscribeAllSubnets-2?expand=1

2022-12-19 08:30 UTC, tuyennhv commented
> Why is using the randomSubscriptionSloLen() here necessary?

@dapplion it's really not necessary, just want to have same code to real random subscriptions, I changed to `Infinity`

2022-12-19 08:46 UTC, dapplion commented
@tuyennhv see in my branch I'm using the existing TTL infra and setting it to infinity. Do you think that approach won't work? See diff between both branches https://github.com/ChainSafe/lodestar/compare/tuyen/more_topic_peers_subscribeAllSubnets...tuyen/more_topic_peers_subscribeAllSubnets-2?expand=1

2022-12-19 08:58 UTC, tuyennhv commented
> @tuyennhv see in my branch I'm using the existing TTL infra and setting it to infinity. Do you think that approach won't work? See diff between both branches https://github.com/ChainSafe/lodestar/compare/tuyen/more_topic_peers_subscribeAllSubnets...tuyen/more_topic_peers_subscribeAllSubnets-2?expand=1

@dapplion  oh I see your idea now, yes that should work, merged that branch to this PR

2022-12-19 10:46 UTC, dapplion approved these changes

2022-12-20 06:14 UTC, twoeths commented
Tested on a mainnet node 

<img width="793" alt="Screen Shot 2022-12-20 at 13 14 01" src="https://user-images.githubusercontent.com/10568965/208596600-c4ae1bb8-35fd-4b12-ae0b-48c9f3b98e14.png">

2022-12-20 06:14 UTC, merged