Fix validator waiting on start
ChainSafe/lodestar pull request #500
Opened 2019-10-03 09:33 UTC by tuyennhv

## Goal
+ Close #414

2019-10-04 06:32 UTC, mpetrunic requested changes

2019-10-04 06:32 UTC, mpetrunic commented on packages/lodestar/src/validator/rpc/abstract.ts
> +  }
I don't think you need this method, you can start interval in "connect" method

2019-10-04 06:32 UTC, mpetrunic commented on packages/lodestar/src/validator/rpc/interface.ts
> +  chainLived: () => void;
I would call this event "beaconChainStarted"

2019-10-05 07:10 UTC, mpetrunic requested changes
lgtm, just one small thing

2019-10-05 07:10 UTC, mpetrunic commented on packages/lodestar/src/validator/validator.ts
> +    this.apiClient.once("beaconChainStarted", this.run.bind(this));
I would put this in start method, it makes more sense

2019-10-05 09:47 UTC, mpetrunic approved these changes

2019-10-06 08:55 UTC, mpetrunic commented
@GregTheGreek labeler?

2019-10-06 09:35 UTC, GregTheGreek commented
Fails on forks unfortunately

2019-10-06 09:36 UTC, GregTheGreek approved these changes

2019-10-06 09:40 UTC, merged