Add dockerized metrics local setup
ChainSafe/lodestar pull request #5173
Opened 2023-02-20 06:42 UTC by dapplion

**Motivation**

Recent modifications to the docker setup prevent it from "just working" for local development

**Description**

Add alternative `docker/docker-compose.local_dev.sh` script that "just works" bringing up latest dashboard from local fs

2023-02-20 06:48 UTC, nflaig requested changes
I guess this is a good solution for now until we figure out something else where we need to duplicate less code.

Should also update this in [CONTRIBUTING.md](https://github.com/ChainSafe/lodestar/blob/f4057cfc3f74e62cdf7452dd4215b482cffd756d/CONTRIBUTING.md?plain=1#L62)

2023-02-20 06:48 UTC, nflaig commented on docker/docker-compose.local_dev.sh
> +docker-compose -f docker/docker-compose.local_dev.yml up --build
new line is missing

2023-02-20 06:56 UTC, nflaig approved these changes

2023-02-20 16:08 UTC, wemeetagain approved these changes

2023-02-20 16:08 UTC, merged

2023-03-21 16:50 UTC, wemeetagain commented
:tada: This PR is included in [v1.6.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.6.0) :tada: