Always add gossip attestations to forkchoice
ChainSafe/lodestar pull request #5259
Opened 2023-03-11 04:24 UTC by tuyennhv

**Motivation**

- Gossip handler: Right now we do early return if beacon node does not have any validators as aggregator on specified subnets, i.e we didn't add gossip attestations to forkchoice in that case

**Description**

- We should always add attestations to forkchoice
- The `attnetsService.shouldProcess` should only decide if we add attestation to our pool to prepare for aggregator's duty later

2023-03-11 09:25 UTC, dapplion requested changes
Are you sure this is required? What problem or correctness issue is it trying to fix?

2023-03-12 09:55 UTC, tuyennhv commented
@dapplion right now we only pass attestations to fork_choice if we have an aggregator on that subnet/slot, I don't see any requirements for that.

I checked from the spec: `Run ``on_attestation`` upon receiving a new ``attestation`` from either within a block or directly on the wire.` => we always have to do that as I understand

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md#on_attestation

also this was instructed from Cayman as I remember, could you double check @wemeetagain ?

2023-03-13 01:43 UTC, dapplion commented
Right, if we have already done the work of verifying the attestation, might as well include it in the fork-choice

2023-03-23 13:47 UTC, wemeetagain approved these changes

2023-03-24 05:08 UTC, dapplion approved these changes

2023-03-24 05:08 UTC, merged

2023-03-28 03:22 UTC, wemeetagain commented
:tada: This PR is included in [v1.7.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.7.0) :tada: