docs: Update contribution.md for conventional commits
ChainSafe/lodestar pull request #5419
Opened 2023-04-25 15:05 UTC by philknows

**Motivation**

As of #5342 , we now enforce conventional commits on our PR titles.

**Description**

This PR adds the requirement to `contributions.md` for future contributors.

2023-04-25 15:27 UTC, nflaig requested changes

2023-04-25 15:27 UTC, nflaig commented on CONTRIBUTING.md
>  - Should be capitalized and written in imperative present tense
No longer capitalized

```suggestion
- Written in imperative present tense
```

2023-04-25 15:27 UTC, nflaig commented on CONTRIBUTING.md
> +> feat: Add Edit on Github button to all the pages
```suggestion
> feat: add Edit on Github button to all the pages
```

2023-04-25 15:29 UTC, nflaig commented on CONTRIBUTING.md
> +> feat: Add Edit on Github button to all the pages
and 2nd thought, this example is kinda bad, maybe adding 2-3 real Lodestar commits as examples would be better

2023-04-27 09:33 UTC, nflaig approved these changes
Looks good to me as an initial version. Might wanna add more guidelines/recommendations later, such as

- define how the commit is structured `type(scope?): subject` and explain different parts in few bullet points (2-3) 
- when to use which `type`, `feat` vs `fix` vs `refactor`
- advocate for using `scope`, this is especially useful in case of Lodestar monorepo, each package can be a scope (or also sub categories like metrics/monitoring), allows to quickly identify what part of the code base the commit modifies and makes the commit history more searchable

2023-04-27 20:16 UTC, wemeetagain approved these changes

2023-04-27 20:16 UTC, merged

2023-04-27 20:34 UTC, nflaig commented
the formatting of examples seems to be messed up, might be better to use bullet points

![image](https://user-images.githubusercontent.com/38436224/234984273-0ede9a74-2611-41e9-8772-7596af8b1a26.png)

2023-05-04 20:25 UTC, wemeetagain commented
:tada: This PR is included in [v1.8.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.8.0) :tada: