Tuyen/do not serialize gossip blocks
ChainSafe/lodestar pull request #5426
Opened 2023-04-27 07:49 UTC by tuyennhv

**Motivation**

Right now when gossipsub deliver a gossip block, we already have serialized data but still have to serialize signed block when persisting to db

**Description**

- Add utility types `WithBytes, WithOptionalBytes`
- chain now process `WithOptionalBytes<BlockInput>`, at gossip we pass in bytes data, for blocks from other flow we keep them as is

Closes #5422

2023-05-05 17:18 UTC, wemeetagain approved these changes, later dismissed
LGTM

2023-05-08 00:09 UTC, dapplion approved these changes

2023-05-08 00:09 UTC, dapplion requested changes

2023-05-08 00:09 UTC, dapplion commented on packages/beacon-node/src/chain/blocks/importBlock.ts
> +    await this.db.block.add(block);
Add metrics here to count the rate of serializedData cache hits

2023-05-08 03:01 UTC, dapplion approved these changes

2023-05-08 03:01 UTC, merged

2023-06-22 02:27 UTC, wemeetagain commented
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada: