[WIP] State transition update for 0.9.0
ChainSafe/lodestar pull request #543
Opened 2019-11-08 23:45 UTC by tuyennhv

## Goal
+ Close #529 
## Progress
- [x] Update state transition
- [x] Unit tests
- [x] e2e tests
- [ ] Spec tests

2019-11-08 23:46 UTC, tuyennhv commented on packages/lodestar/test/unit/cli/commands/deposit.test.ts
> +  // TODO tuyennhv: this happens with other branches
Will double check with other branches and remove

2019-11-12 08:16 UTC, mpetrunic requested changes
LGTM, just few comments

Think you forgot to delete transfer stuff in db

2019-11-12 08:16 UTC, mpetrunic commented on packages/eth2.0-state-transition/src/util/blockRoot.ts
> +    // `state_root` is zeroed and overwritten in the next `process_slot` call
that should go one line above

2019-11-12 08:16 UTC, mpetrunic commented on packages/eth2.0-state-transition/src/util/duties.ts
> + * Return None if no assignment..
Return null :)

2019-11-12 08:16 UTC, mpetrunic commented on packages/lodestar/test/spec/genesis/initialization/genesis_initialization_minimal.test.ts
> +// https://github.com/ChainSafe/lodestar/issues/534
leave this test failing (uncomment), that's perfectly fine, we aren't merging to master

2019-11-12 09:35 UTC, tuyennhv commented
@mpetrunic regarding
> Think you forgot to delete transfer stuff in db
I deleted `transfer.ts` inside`db/**/repositories`. Is it enough? Can't find any "transfer" inside `db/**/repositories` anyway.

2019-11-12 11:39 UTC, mpetrunic submitted a review, later dismissed

2019-11-12 15:43 UTC, wemeetagain approved these changes

2019-11-12 15:47 UTC, merged