test: add transfer / copy benchmark
ChainSafe/lodestar pull request #5470
Opened 2023-05-05 18:47 UTC by wemeetagain

```
  transfer bytes
    ✔ transfer serialized Status (84 B)                                   278784.5 ops/s    3.587000 us/op        -     200446 runs   1.01 s
    ✔ copy serialized Status (84 B)                                       344708.7 ops/s    2.901000 us/op        -     307857 runs   1.01 s
    ✔ transfer serialized SignedVoluntaryExit (112 B)                     291460.2 ops/s    3.431000 us/op        -     230077 runs   1.11 s
    ✔ copy serialized SignedVoluntaryExit (112 B)                         332446.8 ops/s    3.008000 us/op        -     415151 runs   1.41 s
    ✔ transfer serialized ProposerSlashing (416 B)                        235294.1 ops/s    4.250000 us/op        -     168969 runs   1.01 s
    ✔ copy serialized ProposerSlashing (416 B)                            228990.2 ops/s    4.367000 us/op        -     212139 runs   1.01 s
    ✔ transfer serialized Attestation (485 B)                             242895.3 ops/s    4.117000 us/op        -     435085 runs   2.53 s
    ✔ copy serialized Attestation (485 B)                                 259470.7 ops/s    3.854000 us/op        -     427502 runs   1.82 s
    ✔ transfer serialized AttesterSlashing (33232 B)                      255754.5 ops/s    3.910000 us/op        -      73625 runs  0.808 s
    ✔ copy serialized AttesterSlashing (33232 B)                          116563.7 ops/s    8.579000 us/op        -      32696 runs  0.303 s
    ✔ transfer serialized Small SignedBeaconBlock (128000 B)              234192.0 ops/s    4.270000 us/op        -      28611 runs  0.707 s
    ✔ copy serialized Small SignedBeaconBlock (128000 B)                  44865.18 ops/s    22.28900 us/op        -      12291 runs  0.303 s
    ✔ transfer serialized Avg SignedBeaconBlock (200000 B)                200843.5 ops/s    4.979000 us/op        -      13545 runs  0.505 s
    ✔ copy serialized Avg SignedBeaconBlock (200000 B)                    30021.92 ops/s    33.30900 us/op        -       7960 runs  0.303 s
    ✔ transfer serialized BlobsSidecar (524380 B)                         182249.0 ops/s    5.487000 us/op        -      10534 runs  0.909 s
    ✔ copy serialized BlobsSidecar (524380 B)                             12473.03 ops/s    80.17300 us/op        -       4001 runs  0.404 s
    ✔ transfer serialized Big SignedBeaconBlock (1000000 B)               164419.6 ops/s    6.082000 us/op        -       7487 runs   1.27 s
    ✔ copy serialized Big SignedBeaconBlock (1000000 B)                   6638.784 ops/s    150.6300 us/op        -       2004 runs  0.454 s
```

2023-05-07 23:48 UTC, dapplion commented
Using transfer could become a massive runtime bobby trap of unpredictable behavior. After transfer the source ArrayBuffer is mutated into holding no data. So what before returned u8, now returns undefined. I think this is really dangerous behavior I don't want in Lodestar to save a few microseconds

2023-05-07 23:49 UTC, dapplion approved these changes

2023-05-08 11:57 UTC, wemeetagain commented
Actually it throws an error when accessed in worker context

2023-05-09 00:41 UTC, dapplion requested changes

2023-05-09 00:41 UTC, dapplion commented on packages/beacon-node/test/perf/util/transferBytes.test.ts
> +      fn: async () => {
Since this benchmarks are not critical to Lodestar, don't track them as part of CI. Add option `noThreshold` to both of them

2023-05-29 12:15 UTC, dapplion approved these changes

2023-05-29 12:44 UTC, merged

2023-06-22 02:29 UTC, wemeetagain commented
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada: