feat(logger): remove unused trace log level
ChainSafe/lodestar pull request #5861
Opened 2023-08-08 07:55 UTC by matthewkeil

**Motivation**

`trace` does not follow our logging policy and it is broken as well.  Found an error and instead of fixing we decided to remove this. 

**Description**

Removes remnants of `trace`

2023-08-08 08:11 UTC, nflaig commented
What happens if you pass `trace` as log level now from the CLI? See requirement mentioned in https://github.com/ChainSafe/lodestar/issues/4536/.

2023-08-08 08:14 UTC, matthewkeil commented
> What happens if you pass `trace` as log level now from the CLI? See requirement mentioned in #4536.

It will error as it's unsupported per our logging policy.  Should I throw an error on startup stating that its not supported?

2023-08-08 08:22 UTC, nflaig commented
As per issue

>This causes Lodestar startup to fail when trace logging is configured.

> That way trace logging can be enabled for a "stack" consisting of Lodestar, an EL, Grafana, etc.

Right now we break this use case, I would suggest we go with what I suggested in https://github.com/ChainSafe/lodestar/issues/5809#issuecomment-1660358713.

> We should remove it from types to prevent accidental usage but still allow it to be passed through CLI to not break the use case mentioned in https://github.com/ChainSafe/lodestar/issues/4536.

2023-08-08 15:20 UTC, dapplion submitted a review, later dismissed
A runtime error like this is not the best way to handle it

2023-08-08 15:24 UTC, matthewkeil commented
> A runtime error like this is not the best way to handle it

I agree.  Was actually just messaging @nflaig about this on discord.  Was tossing around the idea of just having trace log to the debug LogLevel but that isnt great either because the function can still be used...

Another idea would be to have two "log levels" one for reporting and one for the interface generation so the classes do not export the symbol but passing --trace to the reporting level just outputs debug level.  What do you prefer @dapplion and @nflaig?

2023-08-08 15:49 UTC, nflaig commented
We can simply update the logger interface
https://github.com/ChainSafe/lodestar/blob/e690ac6df8b6c3e766fd5c245254575dad061f7b/packages/utils/src/logger.ts#L4

to something like this

```ts
export type Logger = Record<Exclude<LogLevel, LogLevel.trace>, LogHandler>;
```

This will allow to set `--logLevel trace` while also preventing accidental usage in code

2023-09-22 19:19 UTC, wemeetagain commented
Yeah, would like to see the solutions @nflaig proposed

2023-09-29 15:52 UTC, nflaig requested changes
shouldn't this method be removed here as well?

https://github.com/ChainSafe/lodestar/blob/92cca53f7711debf2f21029344a5bcd5ecb037e1/packages/logger/src/winston.ts#L80

2023-09-29 16:48 UTC, nflaig approved these changes

2023-09-30 12:25 UTC, wemeetagain approved these changes
Lgtm, can you update the PR description with the latest changes / motivation before you merge?

2023-09-30 12:39 UTC, nflaig commented
On that note, does this close https://github.com/ChainSafe/lodestar/issues/5809 as well?

The expected behavior in the issue is
> A trace log should work and not break the other log levels

but after discussion, the expected behavior should rather be what I mentioend in https://github.com/ChainSafe/lodestar/pull/5861#issuecomment-1669872677

> This will allow to set --logLevel trace while also preventing accidental usage in code

2023-10-01 09:22 UTC, matthewkeil commented
@wemeetagain the PR body is updated but cannot merge because of e2e test not closing cleanly.  Ready to merge though I believe.

2023-10-02 02:15 UTC, merged

2023-11-09 07:42 UTC, wemeetagain commented
:tada: This PR is included in [v1.12.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.12.0) :tada: