Add build workflow for debug nodejs
ChainSafe/lodestar pull request #6103
Opened 2023-11-10 13:59 UTC by nazarhussain

**Motivation**

More flexible debugging for native nodejs modules. 

**Description**

- We often need to debug exceptions which are on the native bindings 
- NodeJS debug build provide more information in case of the segfaults or related errors
- We don't have any runner available to have builtin support for debug build for nodejs 
- The Github actions `setup-node` also don't provide this support. 
- The idea is the build once a debug level nodejs binary on same runner we use for tests and upload it to some bucket
- We can then download that binary and in case we need to debug something. 

**Steps to test or reproduce**

-Run all tests.

2023-11-10 14:22 UTC, matthewkeil requested changes

2023-11-10 14:22 UTC, matthewkeil commented on .github/workflows/build-debug-node.yml
> +        run: make -j4
Is it possible to use `make -j$(nproc --all)` here to default to the number of available cores?

2023-11-10 14:22 UTC, matthewkeil commented on .github/workflows/build-debug-node.yml
> +          DESTDIR: ${{ github.workspace }}/nodejs-debug-build-${{ github.event.inputs.version }}
Running `make install` only moves the `Release` version to the `DESTDIR`.  

https://github.com/nodejs/node/blob/609cd7f5bf6c1b2373353fb3fcaed2a3bbe1efa7/tools/install.py#L146

You need to also copy `nodejs/out/Debug/node` binary over the `Release` binary in `DESTDIR/lib/node` (pretty sure about that dest path but not 1000%)

2023-11-10 15:15 UTC, matthewkeil approved these changes
LGTM!! 🚀

2023-11-10 15:32 UTC, merged

2023-12-21 02:00 UTC, wemeetagain commented
:tada: This PR is included in [v1.13.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.13.0) :tada: