chore: update flag to pass builder url
ChainSafe/lodestar pull request #6190
Opened 2023-12-14 09:01 UTC by nflaig

**Motivation**

Lodestar only supports a single builder URL and silently removes fallback URLs if multiple are provided. This behavior is not transparent to the end user and we should be more explicit about it.

**Description**

Update flag to pass builder URL to `--builder.url` (previous flag is kept as alias)

Note that I explicitly removed the support for array and comma-separated values as I think it is better to throw an error on startup then to let the user have wrong assumptions that builder has a fallback configured. I don't know any setup that sets multiple builders but better to have an informative error.

Closes https://github.com/ChainSafe/lodestar/issues/6181

2023-12-18 10:35 UTC, g11tech requested changes
this is a breaking change in cli usage and i don't actually see real need except may be clarifying help on this

2023-12-18 10:45 UTC, nflaig commented
> this is a breaking change in cli usage and i don't actually see real need except may be clarifying help on this

It's not breaking as I kept `builder.urls` as an alias. I opted to throw an error if someone passes multiple URLs (as array is not supported anymore). Alternative would be to keep array support and silently just pick the first URL entry (as we do right now) but I don't think this is great as I already outlined in the PR description.

2023-12-18 11:24 UTC, g11tech approved these changes
lgtm as previous option still works as alias

2023-12-18 11:24 UTC, merged

2023-12-21 02:00 UTC, wemeetagain commented
:tada: This PR is included in [v1.13.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.13.0) :tada: