feat: allow to skip gossip validation
ChainSafe/lodestar pull request #6308
Opened 2024-01-16 11:11 UTC by nazarhussain

**Motivation**

Make sure the block is published to network.

**Description**

In case a node is configured only with the `unknownBlockSync`, it needs to know the unknown parent blocks on the network to initiate the syncing process. Such cases can be covered only if we publish blocks and make sure no gossip validation is performed on those. But this behavior is not the default.

**Steps to test or reproduce**

- Run all tests

2024-01-16 11:16 UTC, nflaig commented on packages/api/src/beacon/routes/beacon/block.ts
> +  none = "none",
Would be good to highlight here that the value is not part of the spec

2024-01-16 11:22 UTC, nazarhussain commented on packages/api/src/beacon/routes/beacon/block.ts
> +  none = "none",
Added.

2024-01-16 14:54 UTC, g11tech requested changes
i can't see you using this flag to setup validator on the tests you are targeting to fix?

2024-01-16 15:19 UTC, wemeetagain approved these changes

2024-01-16 15:36 UTC, nazarhussain commented
> i can't see you using this flag to setup validator on the tests you are targeting to fix?

I will use this in other PR which is ready and need this one to merge first.

2024-01-16 17:54 UTC, g11tech approved these changes

2024-01-16 17:54 UTC, merged

2024-01-29 14:55 UTC, wemeetagain commented
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada: