docs: initialize FAQs page with Kubernetes unknown args error
ChainSafe/lodestar pull request #6416
Opened 2024-02-09 23:54 UTC by philknows

**Motivation**

Closes #6378 

The issue as discussed in [Discord](https://discord.com/channels/593655374469660673/1201684723190210560/1201772954313306112), sparked an idea for us to include a page in our documentation with common questions and known errors that are useful and likely asked by other users. 

**Description**

This PR initializes a FAQ page with a format displayed below using collapsable admonitions for a cleaner visual. This includes our first note to help Kubernetes users deal with env errors.

<img width="1291" alt="Screenshot 2024-02-09 at 6 42 28 PM" src="https://github.com/ChainSafe/lodestar/assets/58080811/191513a2-0182-4dfb-bc21-65326bee8eb2">

2024-02-13 12:39 UTC, nflaig requested changes
This does not explain what the root cause is and how to resolve the issue, will push some updates to this shortly

2024-02-14 11:12 UTC, nflaig commented
Pushed a few updates to better explain root cause and resolution of the issue

![image](https://github.com/ChainSafe/lodestar/assets/38436224/547ead43-10ae-4f69-9039-c071ebd5a0a5)

2024-02-14 12:39 UTC, nflaig approved these changes, later dismissed
Looks good to me now, let's get some more feedback. I really like the layout as it is quite minimal and will also allow us to collapse the sections by default in the future if needed.

2024-02-14 12:45 UTC, nflaig submitted a review, later dismissed

2024-02-14 16:26 UTC, wemeetagain submitted a review, later dismissed

2024-02-14 16:46 UTC, nflaig submitted a review, later dismissed

2024-02-15 04:20 UTC, matthewkeil approved these changes
LGTM!! 🚀   

We definitely should use the details module in some other locations

2024-02-15 04:20 UTC, matthewkeil commented on docs/mkdocs.yml
> +  - pymdownx.details
this is a great add!!!  makes it look really nice

2024-02-15 07:38 UTC, nflaig approved these changes

2024-02-15 07:38 UTC, merged

2024-02-22 14:19 UTC, wemeetagain commented
:tada: This PR is included in [v1.16.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.16.0) :tada: