fix: update broken links to lodestar docs
ChainSafe/lodestar pull request #6417
Opened 2024-02-10 15:40 UTC by krauspt

**Motivation**

I've found that many of links inside several `README.md` files are broken.

**Description**

This PR replaced broken links with working version. Each replaced link was doublechecked to see if works correctly and also maintains the context of original link.

**Steps to test or reproduce**

No testing required.

2024-02-10 15:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=6417) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=6417) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=6417) it.</sub>

2024-02-10 15:48 UTC, philknows approved these changes, later dismissed
Thanks for helping us fix the links! Missed that as we revamped our documentation nav.

2024-02-10 17:00 UTC, nflaig requested changes

2024-02-10 17:00 UTC, nflaig commented on README.md
> +- :globe_with_meridians: Run a beacon node on [mainnet or a public testnet](https://chainsafe.github.io/lodestar/beacon-management/beacon-cli/).
```suggestion
- :globe_with_meridians: Run a beacon node on [mainnet or a public testnet](https://chainsafe.github.io/lodestar/getting-started/starting-a-node/).
```

2024-02-10 17:36 UTC, krauspt commented
@nflaig I've messed this one. Thanks.

2024-02-10 17:57 UTC, nflaig approved these changes
LGTM, thanks for the update @krauspt

2024-02-10 18:11 UTC, merged

2024-02-22 14:19 UTC, wemeetagain commented
:tada: This PR is included in [v1.16.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.16.0) :tada: