Change * value to 'all' for improved bash compatibility ( Issue #5963 )
ChainSafe/lodestar pull request #6459
Opened 2024-02-20 17:06 UTC by clionachee

**Motivation**

The motivation behind this PR is to address issue #5963, which was opened on Sep 18, 2023, by nflaig. The problem described in the issue is that the usage of `"*"` as a value in certain CLI flags is not friendly to use in bash scripts. This is because `*` is interpreted as a wildcard character in bash, rather than as a string. The goal of this PR is to replace the usage of `"*"` with a more bash-friendly value, such as the word "all", to improve compatibility with bash scripts.

**Description**

The changes made in this PR involve replacing the usage of `"*"` with `"all"` in the `enabledAll` variable declaration. This change ensures better compatibility with bash scripts, as `"*"` can cause issues when interpreted as a wildcard character in bash environments. The modification is made in the `api.ts` file located at `lodestar/packages/cli/src/options/beaconNodeOptions/api.ts`, specifically on line 4.

Closes #5963

**Steps to test or reproduce**

2024-02-20 17:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=6459) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=6459) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=6459) it.</sub>

2024-02-22 12:41 UTC, nflaig requested changes
Thanks @clionachee for looking into it.

Please make sure to keep it backward compatible by still supporting "*" as a valid input to enable all namespaces.

Also should make sure to update other references in the code
https://github.com/ChainSafe/lodestar/blob/53f8f99c643698b6c7f2c47b7a9dba200ab44b7b/packages/cli/test/utils/simulation/beacon_clients/lodestar.ts#L42

2024-02-22 12:41 UTC, nflaig commented on packages/cli/src/options/beaconNodeOptions/api.ts
> +const enabledAll = "all";
there is not need to comment the previous behavior
```suggestion
const enabledAll = "all";
```

2024-02-22 12:41 UTC, nflaig commented on packages/cli/src/options/beaconNodeOptions/api.ts
> +    description: `Pick namespaces to expose for HTTP API. Set to '${enabledAll}' to enable all namespaces`, // Updated description
```suggestion
    choices: [...allNamespaces, enabledAll],
    description: `Pick namespaces to expose for HTTP API. Set to '${enabledAll}' to enable all namespaces`,
```

2024-02-22 12:42 UTC, nflaig commented on packages/cli/src/options/beaconNodeOptions/api.ts
> +import { CliCommandOptions } from "../../util/index.js";
formatting

```suggestion
import {defaultOptions, IBeaconNodeOptions, allNamespaces} from "@lodestar/beacon-node";
import {CliCommandOptions} from "../../util/index.js";
```

2024-02-22 12:46 UTC, matthewkeil requested changes
Thank you very much for your submission @clionachee !!!  

If you would be so kind, would you mind added a simple comment to the relevant `cors` flags about needing to quote *?

Please make sure that we are backwards compatible (non-breaking change) so we support existing users.  Thanks!!!

Looks like me and @nflaig both were reviewing concurrently and made the same comments.  Great minds think alike lol

2024-02-22 12:46 UTC, matthewkeil commented on packages/cli/src/options/beaconNodeOptions/api.ts
> +// After: Changed to "all" for better compatibility with bash scripts
Please remove these comments

2024-02-22 12:46 UTC, matthewkeil commented on packages/cli/src/options/beaconNodeOptions/api.ts
> +    description: `Pick namespaces to expose for HTTP API. Set to '${enabledAll}' to enable all namespaces`, // Updated description
Please remove these comments.  They look AI generated 😉

2024-02-25 16:19 UTC, clionachee commented
I've committed the suggestions, are things going well, and thanks for the details in the comments for real. If I overlooked something, please let me know as well. Thanks again.

2024-02-25 17:16 UTC, nflaig commented
Thanks for the updates @clionachee.

We still need to make sure to
- be backward compatible, i.e. if a user passes "*" it should enable all namespaces
- and update namespace references in the code that still pass "*" and replace it with "all"

2024-03-14 20:52 UTC, nflaig commented
@clionachee are you still working on this? Let us know if you need further guidance on how to proceed

2024-03-19 06:09 UTC, clionachee commented
> @clionachee are you still working on this? Let us know if you need further guidance on how to proceed

This is probably a rather dumb question, but about these, where to get go to change them, because I've committed the change. Sorry for any disturbance and thanks a bunch for real.

be backward compatible, i.e. if a user passes "*" it should enable all namespaces
and update namespace references in the code that still pass "*" and replace it with "all"

2024-03-23 10:51 UTC, nflaig commented
> This is probably a rather dumb question, but about these, may I ask where do I get to change them, because I've committed the change. Sorry for any disturbance and thanks a bunch for real.

You can just search the code base for "rest.namespace" to see where it is used. And to add backward compatibility is a simple change in the file you already edited.

You can simply test your changes by using the [Dev CLI command](https://chainsafe.github.io/lodestar/contribution/dev-cli/) to start Lodestar and try different paramets for `--rest.namespace`

2024-03-25 08:41 UTC, clionachee commented
Hi, I searched for `rest.namespace` , `"rest.namespace": "*"` and `*` but it said 'no matches found', so are there any specific string or variations being used? Sorry and thank you very much.

2024-03-25 09:40 UTC, matthewkeil commented
Thank you very much for you help and the attempt to fix this @clionachee!  We really love our community and appreciate your attempt to fix this for us.  If you are still having trouble despite the help from @nflaig I think this may be beyond your current skill level with TypeScript.  Please feel free to do a bit more digging and learning and come back and see us when you are a bit more comfortable with the development workflow.  We will be here waiting for you and will be happy to help when you get some more experience under your belt.  😃

2024-03-25 09:40 UTC, closed without merging