feat: Implement expected withdrawals API
ChainSafe/lodestar pull request #6514
Opened 2024-03-06 10:46 UTC by HiroyukiNaito

**Motivation**

Latest beacon API spec requires expected withdrawals API

**Description**

Implement the following route:

https://ethereum.github.io/beacon-APIs/#/Builder/getNextWithdrawals

Closes #5696

**Steps to test or reproduce**

```sh
curl -X 'GET' \
  'http://localhost/eth/v1/builder/states/head/expected_withdrawals?proposal_slot=1' \
  -H 'accept: application/json'
```

2024-03-06 11:03 UTC, HiroyukiNaito commented
This is a tentative implement. 
Please, do not hesitate to point out if I am in a wrong direction.

2024-03-07 04:23 UTC, ensi321 commented
Thanks for your contribution🙂

> This is a tentative implement.
> Please, do not hesitate to point out if I am in a wrong direction because I'm a new born baby in this field.

Just trying to understand the scope of this PR. Is it only adding the route definition of `getNextWithdrawals`, or is it going to implement the its functionality as well but you are still working on it?

If latter, it would be great if you can mark it as PR draft and reach out to the maintainers on Discord if you need any assistance. If former, I am happy to review it once the CI checks are passed😀

2024-03-07 15:49 UTC, HiroyukiNaito commented
> Thanks for your contribution🙂
> 
> > This is a tentative implement.
> > Please, do not hesitate to point out if I am in a wrong direction because I'm a new born baby in this field.
> 
> Just trying to understand the scope of this PR. Is it only adding the route definition of `getNextWithdrawals`, or is it going to implement the its functionality as well but you are still working on it?
> 
> If latter, it would be great if you can mark it as PR draft and reach out to the maintainers on Discord if you need any assistance. If former, I am happy to review it once the CI checks are passed😀

That would be appreciated! So far, surveying how to implement the API. If both adding Routes and  Types are completed, I would like to ask you to review before the implementation of the function and test.

2024-03-08 10:38 UTC, HiroyukiNaito commented
@ensi321 
Could you please review my code both routes and types when you have a moment before implementing the function?
I'm wondering it is right implement.

2024-03-08 14:33 UTC, HiroyukiNaito commented
I misunderstood  the concept. I will recreate it.

2024-03-11 07:22 UTC, ensi321 requested changes
Good work! Left some comments regarding the route definition

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +    state_id: StateId,
The function parameters should use camel case ie. `stateId` and `proposalSlot`.

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +          finalized: Finalized;
Currently Lodestar doesn't support `finalized` in the apis. You can discard this field for now. See #5693 for more.

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +      parseReq: ({params, query}) => [params.state_id, query.proposal_slot ?? 0],
Do you need a default value for proposal slot if you have defined it as `Slot | undefined`?

2024-03-11 07:22 UTC, ensi321 commented on packages/api/test/unit/builder/testData.ts
> +      finalized: false,
As above, remove `finalized`

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +          finalized: Finalized;
When you remove `finalized` field, don't forget to update `packages/api/test/unit/beacon/oapiSpec.test.ts`. You need to remove `getNextWithdrawals` from `ignoredOperations`, and add `getNextWithdrawals: {response: ["finalized"]},` to `ignoredProperties`

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +import {ssz, allForks, bellatrix, Slot, Root, BLSPubkey, ValidatorIndex, WithdrawalIndex} from "@lodestar/types";
This file is dedicated to [`builder api`](https://ethereum.github.io/builder-specs/#/). The endpoint you are implementing is for `beacon api`. Although they both share the same `/eth/v1/builder/` route, for the purpose for spec compliant and ease of testing, please create a new file `packages/api/src/beacon/routes/builder.ts` and move all the `getExpectedWithdrawals` definition to there

2024-03-11 07:22 UTC, ensi321 commented on packages/api/src/builder/routes.ts
> +  amount: UintNum64;
I would use `number` here since `UintNum64` is ssz related

2024-03-11 07:28 UTC, ensi321 commented
Please convert this PR into PR draft while working on the implementation and convert it back when it's ready for another round of review. You can read more about it [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request)

Maintainers will get notifications every time you commit unless you make this a draft 😅

2024-03-11 07:35 UTC, HiroyukiNaito commented
@ensi321 Great! Thank you for the tips. According to these hints, I will program it again.

2024-03-13 11:49 UTC, HiroyukiNaito commented
@ensi321 

I implemented the interface for getting the withdrawal data.
However,  `curl -X 'GET'   'http://localhost:9596/eth/v1/builder/states/head/expected_withdrawals'   -H 'accept: application/json'` still returns {"message":"Route GET:/eth/v1/builder/states/head/expected_withdrawals not found","error":"Not Found","statusCode":404}. 
It looks failed to route the api. Anything needs to add for routing the API?

2024-03-14 07:36 UTC, ensi321 commented
> @ensi321
> 
> I implemented the interface for getting the withdrawal data. However, `curl -X 'GET' 'http://localhost:9596/eth/v1/builder/states/head/expected_withdrawals' -H 'accept: application/json'` still returns `{"message":"Route GET:/eth/v1/builder/states/head/expected_withdrawals not found","error":"Not Found","statusCode":404}`. It looks failed to route the api. Anything needs to add for routing the API?

You will also need to add a http server for your newly created builder api. 
See https://github.com/ChainSafe/lodestar/blob/87f07fe67d317c250c9d678541d19e9a796111a0/packages/api/src/beacon/server/debug.ts#L1
https://github.com/ChainSafe/lodestar/blob/87f07fe67d317c250c9d678541d19e9a796111a0/packages/api/src/beacon/server/index.ts#L39

https://github.com/ChainSafe/lodestar/blob/87f07fe67d317c250c9d678541d19e9a796111a0/packages/api/src/beacon/index.ts#L14

Lodestar should start serving this route afterwards. Also you will need to define a http client too which is similar to http server. See `packages/api/src/beacon/client/debug.ts`

2024-03-14 10:24 UTC, HiroyukiNaito commented
@ensi321 Thank you so much for taking the time to review the code, especially with your busy schedule.
I could get fake response now before implementating the function.
If you have any correction before that, please do not hesitate to point out.

```bash
 curl -X 'GET'   'http://localhost:9596/eth/v1/builder/states/head/expected_withdrawals'   -H 'accept: application/json'| python3 -m json.tool
{
    "execution_optimistic": false,
    "data": [
        {
            "index": 1,
            "validator_index": 1,
            "address": "0xAbcF8e0d4e9587369b2301D0790347320302cc09",
            "amount": 1
        }
    ]
}
```

2024-03-15 15:07 UTC, HiroyukiNaito commented
Hi, I almost done (exception handlings are not yet) , but, Development network   ./lodestar dev --genesisValidators 8 --reset --rest.namespace "*"  always returns http://localhost:9596/eth/v1/builder/states/head/expected_withdrawals empty array. How do I get getExpectedWithdrawals method  value on this environment? 
Do I need to implement on my mainnet environment for conforming the logic?

2024-03-18 12:26 UTC, ensi321 commented
> Do I need to implement on my mainnet environment for conforming the logic?

I recommend testing this kind of features by running it as a beacon node on mainnet or other public testnet like holesky. I admit it might be hard for contributors who have limited hardwares. 

> Hi, I almost done (exception handlings are not yet) , but, Development network ./lodestar dev --genesisValidators 8 --reset --rest.namespace "*" always returns http://localhost:9596/eth/v1/builder/states/head/expected_withdrawals empty array. How do I get getExpectedWithdrawals method value on this environment?

This is expected. The reason why `getExpectedWithdrawals()` is returning empty list is because 
1) The validators don't have eth1 withdrawal credentials so this condition fails https://github.com/ChainSafe/lodestar/blob/f672c10bcbc828df89f96180a90a5eb0b8138f7f/packages/state-transition/src/block/processWithdrawals.ts#L85
2) The validators are qualified for full or partial withdrawals. The latter is because their balance is 32ETH. See [this](https://github.com/ChainSafe/lodestar/blob/unstable/packages/state-transition/src/block/processWithdrawals.ts#L91) and  [this](https://github.com/ChainSafe/lodestar/blob/f672c10bcbc828df89f96180a90a5eb0b8138f7f/packages/state-transition/src/block/processWithdrawals.ts#L99)

The current `dev` command does a poor job to initiate validators that qualify these two requirements. 


If running a beacon node on mainnet/testnet is too much for you, and wish to test this locally with `dev` command, I recommend to modify the codebase as follow such that validators can meet the two requirements above:
1) Change this line https://github.com/ChainSafe/lodestar/blob/f672c10bcbc828df89f96180a90a5eb0b8138f7f/packages/cli/src/cmds/dev/handler.ts#L63
to `const {state} = nodeUtils.initDevState(config, validatorCount, {genesisTime, eth1BlockHash, withEth1Credentials: true});`
2) Change this line https://github.com/ChainSafe/lodestar/blob/f672c10bcbc828df89f96180a90a5eb0b8138f7f/packages/beacon-node/src/node/utils/interop/deposits.ts#L37 to `amount: MAX_EFFECTIVE_BALANCE + 1,`

Lastly run `./lodestar dev --genesisValidators 8 --reset --rest.namespace "*" --params.ALTAIR_FORK_EPOCH 0 --params.BELLATRIX_FORK_EPOCH 0 --params.CAPELLA_FORK_EPOCH 0 --terminal-total-difficulty-override 0` to activate cappella fork.

I ran this locally and the api returns `getExpectedWithdrawals error - Do not know how to serialize a BigInt
TypeError: Do not know how to serialize a BigInt`.

2024-03-21 16:22 UTC, HiroyukiNaito commented
@ensi321 Thanks! I will resume this soon.

2024-06-13 12:40 UTC, nflaig commented
@HiroyukiNaito Are you planning to continue on this? Since we recently refactored our api framework, most of the changes in this PR are outdated, I suggest to just open a new PR and continue discussion there.


> I recommend testing this kind of features by running it as a beacon node on mainnet or other public testnet like holesky. I admit it might be hard for contributors who have limited hardwares.

Just a side note on this, it's pretty easy to spin up a mainnet node on any device, it just takes 1-2 min on my laptop to startup and be synced to head, you can just run

```sh
./lodestar beacon --checkpointSyncUrl https://beaconstate-mainnet.chainsafe.io --forceCheckpointSync --execution.engineMock
```

This requires ~5-6GB RAM but other than that it's pretty lightweight.

2024-10-10 21:01 UTC, nflaig commented
this PR has too many conflicts since we did a major refactoring of the api layer, it makes sense to tackle this in a new PR

2024-10-10 21:01 UTC, closed without merging