Upgrade geth version in the sim tests
ChainSafe/lodestar pull request #6540
Opened 2024-03-13 11:27 UTC by nazarhussain

**Motivation**

Make the tests more stable. 

**Description**

- Use latest Geth version in the sim tests. 
- Disable the Nethermind untill https://github.com/NethermindEth/nethermind/issues/6683 is resolved. 

**Steps to test or reproduce**

- Run all tests

2024-03-13 11:41 UTC, jeluard requested changes

2024-03-13 11:41 UTC, jeluard commented on .env.test
> +# This is the last verion which supports pre/post merge chains in the same network
```suggestion
# This is the last version which supports pre/post merge chains in the same network
```

2024-03-13 11:41 UTC, jeluard commented on .env.test
> +# Disabling Nethermind from sim tests untill the above issue is resolved
```suggestion
# Disabling Nethermind from sim tests until the above issue is resolved
```

2024-03-13 11:41 UTC, jeluard commented on packages/cli/test/utils/simulation/execution_clients/geth.ts
> +        "--nodiscover",
Curious what this is about?

2024-03-13 11:42 UTC, nazarhussain commented on packages/cli/test/utils/simulation/execution_clients/geth.ts
> +        "--nodiscover",
The newer version automatically start network discovery of nodes, want to block that.

2024-03-13 11:47 UTC, jeluard submitted a review, later dismissed

2024-03-13 12:11 UTC, nflaig approved these changes

2024-03-13 12:46 UTC, merged

2024-04-23 19:04 UTC, wemeetagain commented
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada: