feat: properly consider Eth-Consensus-Version header
ChainSafe/lodestar pull request #6582
Opened 2024-03-22 17:48 UTC by jeluard

**Motivation**

Follow the [beacon-APIs](https://github.com/ethereum/beacon-APIs) specs.

**Description**

Fixes https://github.com/ChainSafe/lodestar/issues/6580

2024-03-25 11:41 UTC, nflaig commented on packages/api/src/beacon/routes/beacon/block.ts
> +    headers: {"eth-consensus-version"?: ForkName};
you can't be sure this is a valid ForkName here

```suggestion
    headers: {"eth-consensus-version"?: string};
```

2024-03-25 11:47 UTC, nflaig commented on packages/api/src/beacon/routes/beacon/block.ts
> +    opts?: {broadcastValidation?: BroadcastValidation; version?: ForkName}
relying on consumer to provide this is not correct, this is mandatory and should be handled internally by the API client

2024-03-25 11:49 UTC, nflaig requested changes
This PR does not address the actual problem noted in https://github.com/ChainSafe/lodestar/issues/6580 that we are not setting the header when sending the request.

As noted in https://github.com/ChainSafe/lodestar/issues/6580#issuecomment-2015055630 I don't think it is worth it to change the behavior on the server at all, current approach works and it compatible with all clients.

Header is still missing
```ts
{
  host: '127.0.0.1:9596',
  connection: 'keep-alive',
  'content-type': 'application/json',
  accept: '*/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'node',
  'accept-encoding': 'gzip, deflate',
  'content-length': '1022'
}
```

2024-03-25 11:49 UTC, nflaig commented on packages/api/src/beacon/routes/beacon/block.ts
> +        const headers = version !== undefined ? {"eth-consensus-version": version} : {};
Version header must be set as per spec, see how this is handled in the refactored api client

https://github.com/ChainSafe/lodestar/blob/c3afb0beaaa5ba9ced4c2c6c68202fecedb18ef3/packages/api/src/beacon/routes/beacon/block.ts#L357-L370

2024-03-26 13:11 UTC, jeluard commented
Superseded by https://github.com/ChainSafe/lodestar/pull/6593

2024-03-26 13:11 UTC, closed without merging