test: fix multi-fork tests
ChainSafe/lodestar pull request #6610
Opened 2024-03-28 14:01 UTC by nazarhussain

**Motivation**

Keep the tests stable. 

**Description**

Fix the multi-fork sim tests. 

**Steps to test or reproduce**

- Run all tests.

2024-03-28 15:06 UTC, nflaig commented on packages/cli/test/sim/multi_fork.test.ts
> +const blobsForUnknownBlockSync = await env.nodes[0].beacon.api.beacon.getBlobSidecars("head");
these operations do not happen atomically and the head might have changed when querying the blob sidecars api, a more safe approach would be to query by slot of the block

2024-03-28 15:06 UTC, nflaig commented on packages/cli/test/sim/multi_fork.test.ts
> +    await unknownBlockSync.beacon.api.beacon.publishBlockV2(
are we always post deneb when calling this api? the request would be invalid pre deneb

2024-03-28 15:29 UTC, nazarhussain commented on packages/cli/test/sim/multi_fork.test.ts
> +    await unknownBlockSync.beacon.api.beacon.publishBlockV2(
Yes we are calling this after all the configured forks. And deneb is the last in the list now.

2024-03-28 15:30 UTC, nazarhussain commented on packages/cli/test/sim/multi_fork.test.ts
> +const blobsForUnknownBlockSync = await env.nodes[0].beacon.api.beacon.getBlobSidecars("head");
If head is behind, the test already failed with proper error message.

2024-03-28 15:32 UTC, nflaig commented on packages/cli/test/sim/multi_fork.test.ts
> +const blobsForUnknownBlockSync = await env.nodes[0].beacon.api.beacon.getBlobSidecars("head");
but can't the head change between those two requests? This would lead to request blob sidecars for a different block

2024-03-28 15:42 UTC, nazarhussain commented on packages/cli/test/sim/multi_fork.test.ts
> +const blobsForUnknownBlockSync = await env.nodes[0].beacon.api.beacon.getBlobSidecars("head");
Theoretically yes.

2024-03-28 16:10 UTC, nflaig approved these changes
LGTM

2024-03-28 16:11 UTC, nflaig requested changes
Acutally, there is an error in multifork sim tests which looks related?

2024-03-29 08:51 UTC, nazarhussain commented
> Acutally, there is an error in multifork sim tests which looks related?

It's not related to this PR.  I observed it only few times, it's stating that tracker didn't closed before the node shutdown. Will look that error separately.

2024-03-29 10:53 UTC, nflaig approved these changes

2024-03-29 10:53 UTC, merged

2024-04-23 19:04 UTC, wemeetagain commented
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada: