feat: add support for web3.js to simulation tests
ChainSafe/lodestar pull request #6641
Opened 2024-04-05 13:47 UTC by nazarhussain

**Motivation**

Add the support for web3.js to simulation tests. 

**Description**

- We need to test some scenarios in future which requires to interact with the EL nodes
- Having custom logic for all interactions will be redundant and error prune 
- Using proven web3.js as ETH RPC client will solve a lot of issues. 

**Steps to test or reproduce**

- Run all tests

2024-04-05 15:23 UTC, matthewkeil requested changes
Really nice addition! Just a couple comments on naming.

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/Web3Plugins.ts
I know the simulation rig has file names in PascalCase but not sure that is the right way to go. Can we name this file `web3JsPlugins.ts`

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/Web3Plugins.ts
> +export function registerWeb3Plugins(web3: Web3): void {
```suggestion
export function registerWeb3JsPlugins(web3: Web3): void {
```

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/execution_clients/geth.ts
> +  const web3 = new Web3(ethRpcPublicUrl);
I think `provider` feels more industry standard in this context.  I tend to like the old way better so its clear what the object does to observers.

```suggestion
  const provider = new Web3(ethRpcPublicUrl);
```

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/execution_clients/nethermind.ts
> +  const web3 = new Web3(ethRpcPublicUrl);
Same as above.  I tend to think `provider` was the correct name.

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/utils/network.ts
> +      // `web3.admin` here refers to the Web3 plugin `Web3AdminPlugin`
I like that you added the note here!

2024-04-05 15:23 UTC, matthewkeil commented on packages/cli/test/utils/simulation/Web3Plugins.ts
> +  pluginNamespace = "admin";
```suggestion
  /**
   * The admin plugin as available via the provider object
   * like in the example below.
   *
   * await node.web3.admin.addPeer(elIdentity.enode);
   */
  pluginNamespace = "admin";
```

2024-04-05 15:37 UTC, nazarhussain commented on packages/cli/test/utils/simulation/Web3Plugins.ts
> I know the simulation rig has file names in PascalCase but not sure that is the right way to go. Can we name this file `web3JsPlugins.ts`

Let's do the renaming of all files in different PR.

2024-04-08 07:52 UTC, matthewkeil approved these changes
LGTM!! 🚀

2024-04-08 07:56 UTC, merged

2024-04-23 19:04 UTC, wemeetagain commented
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada: