chore: reuse setup action
ChainSafe/lodestar pull request #6659
Opened 2024-04-11 07:50 UTC by jeluard

**Motivation**

Reuse existing GitHub action to reduce boilerplate duplication

2024-04-11 07:56 UTC, nazarhussain requested changes

2024-04-11 07:56 UTC, nazarhussain commented on .github/workflows/publish-rc.yml
> -          check-latest: true
Only thing missing would be this check. Could you pass this down to the action as well.

2024-04-11 08:29 UTC, nazarhussain commented on .github/workflows/publish-rc.yml
> -          check-latest: true
Sorry I didn't remember if `build-setup` action already have `check-latest`. Please ignore this comment.

2024-04-11 08:31 UTC, nazarhussain approved these changes

2024-04-11 08:50 UTC, merged

2024-04-23 19:04 UTC, wemeetagain commented
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada: