fix: get seen AttData key from SignedAggregateAndProof electra
ChainSafe/lodestar pull request #6802
Opened 2024-05-17 15:08 UTC by twoeths

**Motivation**

Our AggregateAndProof gossip validation was getting worse in electra devnet-0

<img width="1236" alt="Screenshot 2024-05-17 at 18 06 36" src="https://github.com/ChainSafe/lodestar/assets/10568965/7f46db70-7056-4694-b25c-1b9876bce481">

**Description**

It never hit the cache since we get the wrong Attestation Data key.
- phase0: AttestationData
- electra: AttestationData + CommitteeBits

2024-05-17 15:12 UTC, nazarhussain approved these changes

2024-05-17 15:17 UTC, wemeetagain approved these changes

2024-05-17 15:24 UTC, nflaig approved these changes
LGTM

2024-05-17 15:30 UTC, nflaig requested changes
Buffer.from needs to add `byteOffset` and  `byteLength`

2024-05-17 15:39 UTC, nflaig approved these changes

2024-05-17 15:47 UTC, merged

2024-09-17 19:08 UTC, wemeetagain commented
:tada: This PR is included in [v1.22.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.22.0) :tada: