fix: eth1 provider error logging
ChainSafe/lodestar pull request #6863
Opened 2024-06-07 17:18 UTC by nflaig

**Motivation**

Currently, we will only log the error once if the eth1 provider throws continuous errors with a frequency of < 1min while the intended behavior should be to log at most an error every minute to not be silent about the issue but also not flood the logs with errors.

**Description**

Update `elapsedTimeTracker` to not reset timer if there are intermediate calls before time has passed

Part of https://github.com/ChainSafe/lodestar/issues/6469

2024-06-10 12:07 UTC, nazarhussain requested changes, later dismissed

2024-06-10 12:07 UTC, nazarhussain commented on packages/utils/src/waitFor.ts
> +    if (msSinceLastCall > minElapsedTime) {
I am not in favor of this change in `createElapsedTimeTracker` as it's just to track the total elapsed time without any frequency. 

If there is no other usage then we can rename this to `createTimeFrequencyTracker` or similar to make it clear. 

Or I would better suggest to use the `rateLimiter` here. We have few implementation that we can move to utils and reuse here.

2024-06-10 12:35 UTC, nflaig commented on packages/utils/src/waitFor.ts
> +    if (msSinceLastCall > minElapsedTime) {
It's really unintuitive based on current usage of `createElapsedTimeTracker` that is would reset that timer if there are intermediate calls.

In the test cases, the function is even called `callIfTimePassed` which suggests call code if time passed, e.g. like this
```ts
if (callIfTimePassed()) {
  // run this code after time passed
}
```

The usage in `eth1Provider` is the same, the name of the function is `isOneMinutePassed` which suggest log the error if one minute is passed, irrespective of how many times it called `isOneMinutePassed` in-between.

My suggestion is to either fix `createElapsedTimeTracker`, or to remove it altogether has the only use case right now is in `eth1Provider.ts` and it does not what it is supposed to do there.

2024-06-24 15:03 UTC, wemeetagain approved these changes
This is an improvement wrt the logging behavior.

no opinion on the naming

2024-07-05 14:16 UTC, merged

2024-07-11 16:40 UTC, wemeetagain commented
:tada: This PR is included in [v1.20.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.20.0) :tada: