adding license headers
ChainSafe/lodestar pull request #69
Opened 2018-12-27 20:04 UTC by ChainSafe

2018-12-27 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafeSystems/lodestar_chain?pullRequest=69) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafeSystems/lodestar_chain?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafeSystems/lodestar_chain?pullRequest=69) it.</sub>

2018-12-27 20:14 UTC, ChainSafe commented
#68

2018-12-28 11:23 UTC, ansermino requested changes
Please lint

2018-12-28 22:42 UTC, GregTheGreek requested changes
Please fix merge conflict

2019-01-19 18:11 UTC, GregTheGreek commented
Consulting 3rd party on license requirements.

2019-02-19 20:42 UTC, closed without merging