Fix the validation of aggregate and proof
ChainSafe/lodestar pull request #709
Opened 2020-03-18 01:38 UTC by tuyennhv

## Goal
+ Close #691

2020-03-18 01:39 UTC, tuyennhv commented on packages/lodestar/src/network/gossip/validator.ts
> +      aggregationAndProof.aggregate.data.index,
This is main fix, should be committee index instead of aggregator index

2020-03-18 10:40 UTC, mpetrunic requested changes
Can you write test cases for this, I think it also shouldn't use latest state but not 100%

2020-03-20 03:44 UTC, tuyennhv commented
I think we'll end up with using the same state like the one to validate block in my other PR. Need to apply for other validation too as long as we have a `slot`.

2020-03-25 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/lodestar?pullRequest=709) before we can accept your contribution.<br/><hr/>**Tuyen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/lodestar?pullRequest=709) it.</sub>

2020-03-28 09:23 UTC, tuyennhv commented
Replaced by #760

2020-03-28 09:23 UTC, closed without merging