Integrate with new gossipsub version
ChainSafe/lodestar pull request #727
Opened 2020-03-23 04:24 UTC by tuyennhv

## Goal
+ Close #643

2020-03-23 15:40 UTC, mpetrunic requested changes
Could you apply changes to branch with regular sync. Most of stuff is already there, I think only message cache might nee to be updated

2020-03-23 16:18 UTC, wemeetagain submitted a review, later dismissed

2020-03-24 09:55 UTC, mpetrunic requested changes
I think you just need to pass getMessageId function to super constructor options

2020-03-24 09:55 UTC, mpetrunic commented on packages/lodestar/src/network/gossip/gossipsub.ts
> +const msgIdFn = (message: IGossipMessage): string => Buffer.from(hash(message.data)).toString("base64");
We already have that, it's called getMessageId

2020-03-24 09:55 UTC, mpetrunic commented on packages/lodestar/src/network/gossip/gossipsub.ts
> +    if (this.transformedObjects.get(msgIdFn(message))) {
I've extended IGossipMessage in normalizeInRpcMessage to include messageId

2020-03-25 04:23 UTC, tuyennhv commented
Replaced by #754

2020-03-25 04:23 UTC, closed without merging