feat: make `MAX_REQUEST_BLOB_SIDECARS` and `MAX_BLOBS_PER_BLOCK` configurable
ChainSafe/lodestar pull request #7294
Opened 2024-12-13 01:59 UTC by ensi321

We need to make these two parameters configurable before we implement EIP-7623

- Any function that needs access to `MAX_BLOBS_PER_BLOCK` will need to have `config` passed in
- Move `BlobSidecarsByRootRequest` out of `packages/types` to `packages/beacon-node` since it is now "dynamic' depending on `config.MAX_REQUEST_BLOB_SIDECARS`.
- Any method with ssz response type `BlobSidecarsByRootRequest` will need to access `config`.

Closes #7172

2024-12-13 09:33 UTC, nflaig approved these changes
LGTM - there are a few more constants we should move into config but can be addressed separately

2024-12-13 09:33 UTC, nflaig commented on packages/params/src/index.ts
>  export const MAX_REQUEST_BLOCKS_DENEB = 2 ** 7; // 128
as per spec those should be part of config as well, see [configs/mainnet.yaml#L146](https://github.com/ethereum/consensus-specs/blob/18af2af7e98d5cf6ac40145086622b4590447e9b/configs/mainnet.yaml#L146)

2024-12-13 09:33 UTC, nflaig commented on packages/beacon-node/src/util/types.ts
> +export const BlobSidecarsByRootRequestType = (config: Pick<ChainConfig, "MAX_REQUEST_BLOB_SIDECARS">) =>
I don't think it's helpful to pick just the specific key, this is actually more error prone than making sure the proper config object is passed

2024-12-13 09:33 UTC, nflaig commented on packages/beacon-node/src/network/gossip/topic.ts
> +    for (let index = 0; index < config.MAX_BLOBS_PER_BLOCK; index++) {
just a side note, we should use `BLOB_SIDECAR_SUBNET_COUNT` here instead, currently this does not matter as `BLOB_SIDECAR_SUBNET_COUNT == MAX_BLOBS_PER_BLOCK` but would be good to clean up some open todos left over from Deneb

Will put up a separate PR for that

2024-12-13 09:33 UTC, nflaig commented on packages/types/src/deneb/sszTypes.ts
> -export const BlobSidecarsByRootRequest = new ListCompositeType(BlobIdentifier, MAX_REQUEST_BLOB_SIDECARS);
moving this out of types should be fine as it's not a ssz container defined in the spec, only [specs/deneb/p2p-interface.md?plain=1#L284](https://github.com/ethereum/consensus-specs/blob/18af2af7e98d5cf6ac40145086622b4590447e9b/specs/deneb/p2p-interface.md?plain=1#L284)

2024-12-13 10:47 UTC, nflaig requested changes

2024-12-13 10:47 UTC, nflaig commented on packages/validator/src/util/params.ts
> +    MAX_REQUEST_BLOB_SIDECARS: denebForkRelevant,
`MAX_REQUEST_BLOB_SIDECARS` is part of network config, I don't think we need to check this from the vc side

We might rather wanna add it here
https://github.com/ChainSafe/lodestar/blob/99794d3b261bb50f9a6c7d9f6ca19291b3f30911/packages/validator/src/util/params.ts#L137-L138

2024-12-13 20:32 UTC, nflaig approved these changes

2024-12-13 20:51 UTC, merged

2024-12-20 17:35 UTC, wemeetagain commented
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada: