Eager attestation broadcasting
ChainSafe/lodestar pull request #788
Opened 2020-04-09 10:07 UTC by tuyennhv

## Goal
+ Resolves #705

2020-04-09 12:32 UTC, mpetrunic requested changes

2020-04-09 12:32 UTC, mpetrunic commented on packages/lodestar-validator/src/services/attestation.ts
> +      eventSource.close();
Can you extract this to separate method like "waitForAttestationBlock(slot)"

2020-04-09 21:49 UTC, wemeetagain approved these changes

2020-04-10 07:17 UTC, mpetrunic approved these changes

2020-04-10 07:17 UTC, merged