Handle forkDigest event
ChainSafe/lodestar pull request #856
Opened 2020-04-29 13:35 UTC by tuyennhv

## Goal
+ resolve #824

2020-04-29 16:40 UTC, mpetrunic submitted a review, later dismissed

2020-04-29 16:46 UTC, wemeetagain requested changes
LGTM, minor feedback

2020-04-29 16:46 UTC, wemeetagain commented on packages/lodestar/src/network/gossip/gossip.ts
> +    const forkDigestHash = toHexString(forkDigest).toLowerCase().substring(2);
Minor thing, I think we should just use `toHexString(forkDigest)` or `toHex` from `lodestar-utils` for display, without lower casing or substringing.

2020-04-29 16:46 UTC, wemeetagain commented on packages/lodestar/src/network/metadata/metadata.ts
> +    const forkDigestHash = toHexString(forkDigest).toLowerCase().substring(2);
same here

2020-04-30 07:33 UTC, mpetrunic approved these changes

2020-04-30 17:04 UTC, wemeetagain approved these changes

2020-04-30 17:04 UTC, merged