Add tests for isDoubleVote()
ChainSafe/lodestar pull request #93
Opened 2019-02-08 06:09 UTC by tarasbob

2019-02-08 14:22 UTC, GregTheGreek requested changes

2019-02-08 14:22 UTC, GregTheGreek commented on beaconChain/tests/helpers/stateTransitionHelpers.test.ts
> +const genAttestationData = (slot_: uint64, justifiedEpoch_: uint64): AttestationData => ({
Can we move this function into its own file under `tests/utils/attestation.ts`

Also would be great to mark these as optional parameters, and add function descriptions :)

You can use `/tests/utils/validator.ts` as an example

2019-02-08 18:05 UTC, tarasbob commented on beaconChain/tests/helpers/stateTransitionHelpers.test.ts
> +const genAttestationData = (slot_: uint64, justifiedEpoch_: uint64): AttestationData => ({
Done

2019-02-09 02:41 UTC, GregTheGreek approved these changes

2019-02-10 18:11 UTC, wemeetagain approved these changes

2019-02-10 18:26 UTC, merged